### ISSUE TITLE
在typescript写的koa2中使用的问题

### ISSUE THREAD

**Issue by haoliqiang** [hyj1991/easy-monitor#10]
![image](https://user-images.githubusercontent.com/7285671/27572600-77587e6a-5b3f-11e7-8516-693531e2f9aa.png)
![image](https://user-images.githubusercontent.com/7285671/27572634-a4dbd36e-5b3f-11e7-933a-2d3253fbefe6.png)

**Comment by haoliqiang** [comment]
图一是按照文档直接抄的，但是运行项目后，却报图二的错

**Comment by hyj1991** [comment]
@haoliqiang ts 写的确实没有测试过，我要尝试下看看原因，晚上给回复~

**Comment by hyj1991** [comment]
@haoliqiang Hi，我本地用 ts-node 测试一点简单的 ts 代码，没遇到你说的问题，有更多的代码信息可以贴出来排查下吗？

**Comment by haoliqiang** [comment]
@hyj1991 我找到问题原因了，我开启了inspect模式，具体scripts是： "start": "nodemon --inspect -w src -x ts-node src/app.ts",顺便测试了一个开启--debug模式也会报错

**Comment by haoliqiang** [comment]
这个不可以和调试模式一块用么？

**Comment by hyj1991** [comment]
@haoliqiang 这个问题我确认跟踪下，确实没有这样尝试过

**Comment by hyj1991** [comment]
@haoliqiang 问题已经查到了

```inspect``` 模式下，process.execArgv 参数会自动带上 **--inspect**，主进程启动后判断有这个参数会启动 debug-server，但是 Easy-Monitor 设计的时候默认部署模式下 dashboard 使用 child_process.fork 启动，这时候 fork 出来的子进程的 process.execArgv 参数同样会自动带上 **--inspect** 参数，这样 node 认为 fork 出来的子进程也需要启动一个 debug-server，但是因为主进程已经启动了一个 debug-server 了，端口已经被占用，因此 fork 出来的进程永远启动 debug-server 失败，导致 dashboard 进程一直起不来。

这个算是 inspect 和自带的 debug 工具对多进程断点调试支持不够好，当然我也可以在 fork 的时候手动传入参数指定 ```execArgv: []```，下一个版本会解决掉这个问题，预计周五发布。

最后再次感谢下提供这样有用的信息~

**Comment by hyj1991** [comment]
@haoliqiang 已修复默认模式下的支持 --debug 和 --inspect，下一个版本合并

(default deployment mode supports --inspect and --debug)[https://github.com/hyj1991/easy-monitor/commit/010bdb7bfe6056ca9c3221ff2544d559dae1278c]

**Comment by haoliqiang** [comment]
@hyj1991 赞

**Comment by hyj1991** [comment]
已解决
