### ISSUE TITLE
【安装错误】

### ISSUE THREAD

**Issue by SaltFish001** [hyj1991/easy-monitor#100]
按issues中的方式依旧无法安装，还是报错
`
> v8-profiler-node8@6.0.1 preinstall I:\REconsitution\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@6.0.1 install I:\REconsitution\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for v8-profiler-node8@6.0.1 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  profiler.cc
  cpu_profiler.cc
  cpu_profile.cc
  cpu_profile_node.cc
i:\reconsitution\node_modules\v8-profiler-node8\src\cpu_profiler.cc(38): warning C4996: 'v8::Value::ToBoolean': 被声明为已否决 [I:\REconsitution\node_modules\v8-profiler-node8\build\profiler.vcxproj]
  c:\users\12188\.node-gyp\10.15.3\include\node\v8.h(10034): note: 参见“v8::Value::ToBoolean”的声明
i:\reconsitution\node_modules\v8-profiler-node8\src\cpu_profiler.cc(73): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [I:\REconsitution\node_modules\v8-profiler-node8\build\profiler.vcxpro
j]
  c:\users\12188\.node-gyp\10.15.3\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
  heap_profiler.cc
  heap_snapshot.cc
  heap_output_stream.cc
  heap_graph_node.cc
i:\reconsitution\node_modules\v8-profiler-node8\src\heap_snapshot.cc(62): warning C4996: 'v8::Value::Int32Value': 被声明为已否决i:\reconsitution\node_modules\v8-profiler-node8\src\heap_profiler.cc(11
4): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [I:\REconsitution\node_modules\v8-profiler-node8\build\profiler.vcxproj]

  c:\users\12188\.node-gyp\10.15.3\include\node\v8.h(2478): note: 参见“v8::Value::Int32Value”的声明c:\users\12188\.node-gyp\10.15.3\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明

i:\reconsitution\node_modules\v8-profiler-node8\src\heap_snapshot.cc(74): warning C4996: 'v8::Value::Int32Value': 被声明为已否决 [I:\REconsitution\node_modules\v8-profiler-node8\build\profiler.vcxpro
j]
  c:\users\12188\.node-gyp\10.15.3\include\node\v8.h(2478): note: 参见“v8::Value::Int32Value”的声明
i:\reconsitution\node_modules\v8-profiler-node8\src\heap_graph_node.cc(70): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [I:\REconsitution\node_modules\v8-profiler-node8\build\profiler.vcxpro
j]
  c:\users\12188\.node-gyp\10.15.3\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
  heap_graph_edge.cc
C:\Users\12188\.node-gyp\10.15.3\x64\node.lib : fatal error LNK1127: 库已损坏 [I:\REconsitution\node_modules\v8-profiler-node8\build\profiler.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\12188\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\12188\\AppData\\Roaming\\nvm\\v10.15.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=I:\\REconsitution\\node_modules\\v8-profiler-node8\\build\\profiler\\v6.0.1\\node-v64-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=I:\\REconsitution\\node_modules\\v8-profiler-node8\\build\\profiler\\v6.0.1\\node-v64-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"`

**Comment by SaltFish001** [comment]
VS:2017,windows:10,node:10.15.3

**Comment by hyj1991** [comment]
你编译的时候下载的 `node.lib` 好像有问题，试下手动下载：https://nodejs.org/download/release/v10.15.3/win-x86/node.lib，然后替换掉 `C:\Users\12188.node-gyp\10.15.3\x64\node.lib` 这里的文件试试看呢？

**Comment by hyj1991** [comment]
我在  win10 下用 node-v10.15.3 安装 `v8-profiler-node8` 并无问题：

![image](https://user-images.githubusercontent.com/19908330/58762805-24bd2c00-8586-11e9-8dd2-cecbaeebcd39.png)

**Comment by SaltFish001** [comment]
确实是node.lib的问题，我删除重新安装node-gyp后成功了@hyj1991

**Comment by hyj1991** [comment]
#102
