### ISSUE TITLE
monitor启动后 监控网页打不开

### ISSUE THREAD

**Issue by chenws1999** [hyj1991/easy-monitor#101]
node版本: 10.15.3
系统版本: ubuntu 16.4.1

安装easy-monitor时候的log:
`> v8-profiler-node8@6.0.1 preinstall /home/test/other/project/packages/bespoke/game/stock/ss/node_modules/v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@6.0.1 install /home/test/other/project/packages/bespoke/game/stock/ss/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for v8-profiler-node8@6.0.1 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error getaddrinfo EAI_AGAIN node-inspector.s3.amazonaws.com node-inspector.s3.amazonaws.com:443 
make: Entering directory '/home/test/other/project/packages/bespoke/game/stock/ss/node_modules/v8-profiler-node8/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
../src/cpu_profiler.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::CpuProfiler::StartProfiling(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/cpu_profiler.cc:38:42: warning: ‘v8::Local<v8::Boolean> v8::Value::ToBoolean() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     bool recsamples = info[1]->ToBoolean()->Value();
                                          ^
In file included from /home/test/.node-gyp/10.15.3/include/node/v8-profiler.h:10:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/test/.node-gyp/10.15.3/include/node/v8.h:10034:16: note: declared here
 Local<Boolean> Value::ToBoolean() const {
                ^
../src/cpu_profiler.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::CpuProfiler::SetSamplingInterval(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/cpu_profiler.cc:73:68: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     current_cpu_profiler->SetSamplingInterval(info[0]->Uint32Value());
                                                                    ^
In file included from /home/test/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /home/test/.node-gyp/10.15.3/include/node/v8-profiler.h:10,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/test/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/test/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
  CXX(target) Release/obj.target/profiler/src/cpu_profile.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile_node.o
  CXX(target) Release/obj.target/profiler/src/heap_profiler.o
../src/heap_profiler.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::HeapProfiler::GetObjectByHeapObjectId(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/heap_profiler.cc:114:48: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     SnapshotObjectId id = info[0]->Uint32Value();
                                                ^
In file included from /home/test/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /home/test/.node-gyp/10.15.3/include/node/v8-profiler.h:10,
                 from ../src/heap_profiler.h:4,
                 from ../src/heap_profiler.cc:1:
/home/test/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/test/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
  CXX(target) Release/obj.target/profiler/src/heap_snapshot.o
../src/heap_snapshot.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Snapshot::GetNode(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/heap_snapshot.cc:62:41: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     int32_t index = info[0]->Int32Value();
                                         ^
In file included from /home/test/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /home/test/.node-gyp/10.15.3/include/node/v8-profiler.h:10,
                 from ../src/heap_snapshot.h:4,
                 from ../src/heap_snapshot.cc:1:
/home/test/.node-gyp/10.15.3/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/test/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/heap_snapshot.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Snapshot::GetNodeById(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/heap_snapshot.cc:74:47: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     SnapshotObjectId id = info[0]->Int32Value();
                                               ^
In file included from /home/test/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /home/test/.node-gyp/10.15.3/include/node/v8-profiler.h:10,
                 from ../src/heap_snapshot.h:4,
                 from ../src/heap_snapshot.cc:1:
/home/test/.node-gyp/10.15.3/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/test/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
  CXX(target) Release/obj.target/profiler/src/heap_output_stream.o
  CXX(target) Release/obj.target/profiler/src/heap_graph_node.o
../src/heap_graph_node.cc: In static member function ‘static v8::Local<v8::Value> nodex::GraphNode::New(const v8::HeapGraphNode*)’:
../src/heap_graph_node.cc:70:47: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       graph_node = _cache->Get(_id)->ToObject();
                                               ^
In file included from /home/test/.node-gyp/10.15.3/include/node/v8-profiler.h:10:0,
                 from ../src/heap_graph_node.h:4,
                 from ../src/heap_graph_node.cc:1:
/home/test/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^
  CXX(target) Release/obj.target/profiler/src/heap_graph_edge.o
  SOLINK_MODULE(target) Release/obj.target/profiler.node
  COPY Release/profiler.node
  COPY /home/test/other/project/packages/bespoke/game/stock/ss/node_modules/v8-profiler-node8/build/profiler/v6.0.1/node-v64-linux-x64/profiler.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/test/other/project/packages/bespoke/game/stock/ss/node_modules/v8-profiler-node8/build'

> nodemon@1.19.0 postinstall /home/test/other/project/packages/bespoke/game/stock/ss/node_modules/nodemon
> node bin/postinstall || exit 0
`
但是最后安装成功了

在项目中引入并启动之后,输出log
[Easy-Monitor: dashboard <11988>] http_server start at 12333...
[Easy-Monitor: dashboard <11988>] tcp_server start at 26666...
[Easy-Monitor: embrace <11972>] connect to 127.0.0.1:26666 success...

但是随后访问 localhost:12333 和 localhost:26666都打不开

**Comment by hyj1991** [comment]
没有其它错误？试下访问 127.0.0.1:12333 呢

**Comment by chenws1999** [comment]
@hyj1991  都打不开。。。没有响应。。。。

**Comment by hyj1991** [comment]
确认下这里的 https://github.com/hyj1991/easy-monitor/blob/master/src_logic/dashboard/index.js#L38 http 服务器已经正确启动了

或者给个最小复现仓库代码，不然这点信息无法判断为什么 12333 端口没有打开。

**Comment by hyj1991** [comment]
没有其它信息我先关闭了，如果有更多复现信息可以在这里贴出来我看下
