### ISSUE TITLE
启动时报以下错误,然后打开监控web页解析类型只能选择OS

### ISSUE THREAD

**Issue by Choicc** [hyj1991/easy-monitor#102]
启动时:
`[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v6.0.1/node-v64-win32-x64/profiler.node'
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v6.0.1/node-v64-win32-x64/profiler.node'
[Easy-Monitor: dashboard <2576>] http_server start at 12333...
[Easy-Monitor: dashboard <2576>] tcp_server start at 26666...
[Easy-Monitor: embrace <9024>] connect to 127.0.0.1:26666 success...`

npm install easy-monitor 时曾出现过以下信息:

E:\ccy\imm>npm install easy-monitor

> v8-profiler-node8@6.0.1 preinstall E:\ccy\imm\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@6.0.1 install E:\ccy\imm\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for v8-profiler-node8@6.0.1 and node@10.15.2 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by hyj1991** [comment]
`v8-profiler-node8` 安装失败了，你手动安装下贴完整的错误日志看看：

```bash
npm install v8-profiler-node8
```

**Comment by Choicc** [comment]
> `v8-profiler-node8` 安装失败了，你手动安装下贴完整的错误日志看看：
> 
> ```shell
> npm install v8-profiler-node8
> ```

E:\ccy\imm>npm install v8-profiler-node8
npm WARN rm not removing E:\ccy\imm\node_modules\.bin\rimraf.cmd as it wasn't installed by E:\ccy\imm\node_modules\_rimraf@2.6.3@rimraf
npm WARN rm not removing E:\ccy\imm\node_modules\.bin\rimraf as it wasn't installed by E:\ccy\imm\node_modules\_rimraf@2.6.3@rimraf
npm WARN rm not removing E:\ccy\imm\node_modules\.bin\mime.cmd as it wasn't installed by E:\ccy\imm\node_modules\_mime@2.4.4@mime
npm WARN rm not removing E:\ccy\imm\node_modules\.bin\mime as it wasn't installed by E:\ccy\imm\node_modules\_mime@2.4.4@mime

> v8-profiler-node8@6.0.1 preinstall E:\ccy\imm\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'


> v8-profiler-node8@6.0.1 install E:\ccy\imm\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for v8-profiler-node8@6.0.1 and node@10.15.2 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  profiler.cc
  cpu_profiler.cc
  cpu_profile.cc
  cpu_profile_node.cc
  heap_profiler.cc
  heap_snapshot.cc
  heap_output_stream.cc
  heap_graph_node.cc
e:\ccy\imm\node_modules\v8-profiler-node8\src\cpu_profiler.cc(38): warning C4996: 'v8::Value::ToBoolean': 被声明为已否决 [E:\ccy\imm\node_modules\v8-profil
er-node8\build\profiler.vcxproj]
  c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(10034): note: 参见“v8::Value::ToBoolean”的声明
e:\ccy\imm\node_modules\v8-profiler-node8\src\cpu_profiler.cc(73): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [E:\ccy\imm\node_modules\v8-prof
iler-node8\build\profiler.vcxproj]
  c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
e:\ccy\imm\node_modules\v8-profiler-node8\src\heap_profiler.cc(114): warning C4996: 'v8::Value::Uint32Value': 被声明为已否决 [E:\ccy\imm\node_modules\v8-pr
ofiler-node8\build\profiler.vcxproj]
  c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(2477): note: 参见“v8::Value::Uint32Value”的声明
e:\ccy\imm\node_modules\v8-profiler-node8\src\heap_graph_node.cc(70): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [E:\ccy\imm\node_modules\v8-prof
iler-node8\build\profiler.vcxproj]
  c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(10046): note: 参见“v8::Value::ToObject”的声明
e:\ccy\imm\node_modules\v8-profiler-node8\src\heap_snapshot.cc(62): warning C4996: 'v8::Value::Int32Value': 被声明为已否决 [E:\ccy\imm\node_modules\v8-prof
iler-node8\build\profiler.vcxproj]
  c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(2478): note: 参见“v8::Value::Int32Value”的声明
e:\ccy\imm\node_modules\v8-profiler-node8\src\heap_snapshot.cc(74): warning C4996: 'v8::Value::Int32Value': 被声明为已否决 [E:\ccy\imm\node_modules\v8-prof
iler-node8\build\profiler.vcxproj]
  c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(2478): note: 参见“v8::Value::Int32Value”的声明
  heap_graph_edge.cc
C:\Users\Administrator\.node-gyp\10.15.2\x64\node.lib : fatal error LNK1127: 库已损坏 [E:\ccy\imm\node_modules\v8-profiler-node8\build\profiler.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\ccy\\imm\\node_modules\\v8-profiler-node8\\build\\profiler\\v6.0.1\\node-v64-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=E:\\ccy\\imm\\node_modules\\v8-profiler-node8\\build\\profiler\\v6.0.1\\node-v64-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd E:\ccy\imm\node_modules\v8-profiler-node8
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\ccy\imm\node_modules\v8-profiler-node8\build\profiler\v6.0.1\node-v64-win32-x64\profiler.node --module_name=profiler --module_path=E:\ccy\imm\node_modules\v8-profiler-node8\build\profiler\v6.0.1\node-v64-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\ccy\imm\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\ccy\\imm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\ccy\imm\node_modules\v8-profiler-node8
node-pre-gyp ERR! node -v v10.15.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\ccy\imm\node_modules\v8-profiler-node8\build\profiler\v6.0.1\node-v64-win32-x64\profiler.node --module_name=profiler --module_path=E:\ccy\imm\node_modules\v8-profiler-node8\build\profiler\v6.0.1\node-v64-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN imm@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@6.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@6.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-06-10T07_02_54_769Z-debug.log

**Comment by hyj1991** [comment]
参考下这个 issue: https://github.com/hyj1991/easy-monitor/issues/100#issuecomment-498036143，应该是一样的问题

**Comment by hyj1991** [comment]
#100

**Comment by Choicc** [comment]
> 参考下这个 [issue#100](https://github.com/hyj1991/easy-monitor/issues/100#issuecomment-498036143)，应该是一样的问题

你好,我在win7环境下没找到相关路径和文件

**Comment by hyj1991** [comment]
就是重新装下 `node-gyp`

**Comment by hyj1991** [comment]
你安装的 `node-gyp` 有问题，`C:\Users\Administrator.node-gyp\10.15.2\x64\node.lib` node 动态库链接失败了

**Comment by Choicc** [comment]
> 你安装的 `node-gyp` 有问题，`C:\Users\Administrator.node-gyp\10.15.2\x64\node.lib` node 动态库链接失败了

感谢,解决了

**Comment by hyj1991** [comment]
好的，那我关闭了

**Comment by SaltFish001** [comment]
> 你安装的 `node-gyp` 有问题，`C:\Users\Administrator.node-gyp\10.15.2\x64\node.lib` node 动态库链接失败了
我现在也是这个问题，但是安装v8-profiler-node8没报错
> v8-profiler-node8@6.0.1 preinstall F:\REconsitution\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'


> v8-profiler-node8@6.0.1 install F:\REconsitution\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for v8-profiler-node8@6.0.1 and node@8.15.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error connect ETIMEDOUT 52.219.73.6:443
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  profiler.cc
  cpu_profiler.cc
  cpu_profile.cc
  cpu_profile_node.cc
  heap_profiler.cc
  heap_snapshot.cc
  heap_output_stream.cc
  heap_graph_node.cc
  heap_graph_edge.cc
f:\reconsitution\node_modules\v8-profiler-node8\src\heap_snapshot.cc(101): warning C4244: “参数”: 从“int64_t”转换到“uint32_t”
，可能丢失数据 [F:\REconsitution\node_modules\v8-profiler-node8\build\profiler.vcxproj]
f:\reconsitution\node_modules\nan\nan_new.h(208): warning C4244: “参数”: 从“A0”转换到“double”，可能丢失数据 [F:\REconsitution\node_m
odules\v8-profiler-node8\build\profiler.vcxproj]
          with
          [
              A0=int64_t
          ] (编译源文件 ..\src\cpu_profile.cc)
  f:\reconsitution\node_modules\v8-profiler-node8\src\cpu_profile.cc(82): note: 参见对正在编译的函数 模板 实例化“v8::Local<v8::Number>
   Nan::New<v8::Number,int64_t>(A0)”的引用
          with
          [
              A0=int64_t
          ]
f:\reconsitution\node_modules\nan\nan_new.h(208): warning C4244: “参数”: 从“A0”转换到“double”，可能丢失数据 [F:\REconsitution\node_m
odules\v8-profiler-node8\build\profiler.vcxproj]
          with
          [
              A0=size_t
          ] (编译源文件 ..\src\heap_graph_node.cc)
  f:\reconsitution\node_modules\v8-profiler-node8\src\heap_graph_node.cc(126): note: 参见对正在编译的函数 模板 实例化“v8::Local<v8::Nu
  mber> Nan::New<v8::Number,size_t>(A0)”的引用
          with
          [
              A0=size_t
          ]
    正在创建库 F:\REconsitution\node_modules\v8-profiler-node8\build\Release\profiler.lib 和对象 F:\REconsitution\node_modules\
  v8-profiler-node8\build\Release\profiler.exp
  正在生成代码
  已完成代码的生成
  profiler.vcxproj -> F:\REconsitution\node_modules\v8-profiler-node8\build\Release\\profiler.node
  Copying F:\REconsitution\node_modules\v8-profiler-node8\build\Release\/profiler.node to F:/REconsitution/node_modules
  /v8-profiler-node8/build/profiler/v6.0.1/node-v57-win32-x64\profiler.node
  已复制         1 个文件。

> core-js-pure@3.1.3 postinstall F:\REconsitution\node_modules\core-js-pure
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@5.0.1 postinstall F:\REconsitution\node_modules\electron
> node install.js

npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'F:\REconsitution\node_modules\jest-haste-map\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ easy-monitor@2.2.7
added 265 packages from 229 contributors, removed 44 packages, updated 1939 packages and audited 904903 packages in 269.125s
found 12 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
