### ISSUE TITLE
没有找到对应的进程PID

### ISSUE THREAD

**Issue by zsEight** [hyj1991/easy-monitor#104]
[https://locals-house-prod.oss-cn-shenzhen.aliyuncs.com//localhomeqy/public/WechatIMG187.jpeg](url)
[https://locals-house-prod.oss-cn-shenzhen.aliyuncs.com//localhomeqy/public/WechatIMG188.png](url)
请教一下，我的项目部署在docker容器里面，
在easy-monitor页面上没有找到阿里云机器中对应的进程PID，
这是什么原因导致的？

**Comment by hyj1991** [comment]
没遇到过这种情况，需要更多的信息

**Comment by zsEight** [comment]
我不确定需要提供什么信息。
项目框架是egg.js，node版本是v10.15.0，docker容器，两台机器，通过Nginx做分发的。
插件引入位置在app.js头部：
![1563959134956](https://user-images.githubusercontent.com/22189711/61780538-4f648c00-ae35-11e9-8cfa-e05808cdf197.jpg)
项目启动时输出的日志是：
<img width="737" alt="WeChat1d44dcb9502af706402dcae7dd5ecb83" src="https://user-images.githubusercontent.com/22189711/61781010-27c1f380-ae36-11e9-996f-89c5eb76cee7.png">

**Comment by hyj1991** [comment]
你是集群部署方式还是单机？

**Comment by zsEight** [comment]
> 你是集群部署方式还是单机？

集群部署

**Comment by hyj1991** [comment]
那你要配置客户端的 ip 指向你的 dashboard，127.0.0.1 就是本机的 dashboard

**Comment by zsEight** [comment]
> 那你要配置客户端的 ip 指向你的 dashboard，127.0.0.1 就是本机的 dashboard

<img width="539" alt="WeChat113fce5ace7580cdd0069c8514542437" src="https://user-images.githubusercontent.com/22189711/61788310-63fc5080-ae44-11e9-921d-70db34ef4485.png">
请问是这样配置吗，我现在的配置无法打开监听页面

**Comment by hyj1991** [comment]
那还是指向本地的 dashbord，你要把 ip 指向单独部署 dashboard 的地方

**Comment by hyj1991** [comment]
先关闭了，如果有更多的信息可以重新打开讨论
