### ISSUE TITLE
做CPU解析的时候，火焰图暂无数据

### ISSUE THREAD

**Issue by EDArthas** [hyj1991/easy-monitor#105]
难道是程序性能优良的表现？

**Comment by EDArthas** [comment]
补充一下，
环境 Win2008 R2 SP1 64bit，Node 8.16.0 64bit
程序类型: tcp服务器

**Comment by hyj1991** [comment]
你还别说，真的可能是这样。

不过我这里默认会过滤掉系统函数和 node_modules 下的库函数，你可以关闭这个选项再跑次看看：

![image](https://user-images.githubusercontent.com/19908330/62185258-4bd08800-b394-11e9-8f78-c8881d0368c6.png)

实际上从 node 8 开始接入 turbofan 优化编译器后，以前 crankshaft 无法优化的 `try catch`, `switch` 和 `yield` 等流控制相关的代码现在都可以优化了，所以你找不到什么奇怪的热点也正常

**Comment by EDArthas** [comment]
![image](https://user-images.githubusercontent.com/44779376/62186505-18dcc300-b399-11e9-94bc-8480f49b4194.png)
果然，关闭自定义过滤就可以了，多谢

**Comment by hyj1991** [comment]
嗯，你的应用其实什么都没做，没有你自己函数执行的统计
