### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by whitekyo** [hyj1991/easy-monitor#106]
安装教程安装完成之后，用了一个有内存泄漏的demo，用压测跑了一下，任务管理器里的内存将近99%。 easy-monitor显示正常，没有发现任何问题。请问是操作姿势有啥问题吗？

**Comment by hyj1991** [comment]
这个泄露算法很久没更新了，确实是存在缺陷的，例如：#75

目前在计划做 3.0 版本，可以关注下
