### ISSUE TITLE
多次进行内存采集会导致内存溢出

### ISSUE THREAD

**Issue by whu12yz** [hyj1991/easy-monitor#108]
多次对同一节点进行内存采集会导致节点内存溢出

**Comment by hyj1991** [comment]
多次进行内存快照，理论上只会增大堆外部分（v8 内置的序列化接口需要消耗堆外的内存），我试了下多次快照也不会 crash，除非是你的系统物理内存不够了。

**Comment by hyj1991** [comment]
你可以给个复现的方式我来确认下
