### ISSUE TITLE
文档中左侧点击异常

### ISSUE THREAD

**Issue by ericjjj** [hyj1991/easy-monitor#11]
多点击几次就会复现
![image](https://user-images.githubusercontent.com/12462602/27578158-d4fdf336-5b55-11e7-881f-2a89a6477c60.png)

**Comment by hyj1991** [comment]
@ericjjj 这个问题我也发现了，是 Docsify 这个工具的 Bug，我的文档是用 Docsify 生成的，坐等作者修复吧~

**Comment by ericjjj** [comment]
好的 非常好看 借鉴借鉴 我拿去改改 pm86 去

**Comment by hyj1991** [comment]
@ericjjj 期待~
