### ISSUE TITLE
easy-monitor支持load本地的heapdump文件吗

### ISSUE THREAD

**Issue by suutaku** [hyj1991/easy-monitor#112]
进程内存泄漏需要长时间的时间才能复现，复现后进程因为CPU和内存占用太多，基本动不了，easy-monitor也响应不了，所以用代码定时dump了很多文件。如果easy-monitor能够本地load文件进去分析那就太好了。

**Comment by hyj1991** [comment]
试试看 https://www.aliyun.com/product/nodejs

**Comment by suutaku** [comment]
> 试试看 https://www.aliyun.com/product/nodejs

试了一下午，阿里的配置好后，一点击抓取就会Kill掉进程，而且中途会断开。

**Comment by hyj1991** [comment]
@suutaku 可以加钉钉群 **11794270** ，有同学会给你答疑的。按理你这个现象应该是不会出现的。

**Comment by hyj1991** [comment]
alinode 来说的话，其实功能会更强大一些，以前我也是里面的核心开发者，阿里内部的 node.js 项目基本都接入了，但是确实没有 electron 的项目尝试。

**Comment by suutaku** [comment]
好的，我加群和各位交流下。

**Comment by hyj1991** [comment]
先关闭了
