### ISSUE TITLE
服务器内部错误 详情: Error: Network Error, Please refresh this page! 

### ISSUE THREAD

**Issue by amit-gshe** [hyj1991/easy-monitor#113]
这边对docker容器安装这个监控, 然后暴露12333端口, 在采集的时候, 容器的cpu占用100%很长一段时间, 无法对外提供服务, 我必须关闭容器健康检测才不会被docker deamon杀掉, 但最后容器还是退出了, 报了这个错误.
![深度截图_选择区域_20191125104719](https://user-images.githubusercontent.com/7383028/69508585-38fc4780-0f71-11ea-89eb-b00800a11870.png)

**Comment by hyj1991** [comment]
采集之前 cpu 正常么，这里的 cpu 采集，其实就是调用了 v8 里面提供的 `StartProfiling`，并没有其他的操作。

**Comment by amit-gshe** [comment]
我看readme上只兼容8-10, 所以我将镜像的nodejs切到了10, 但出现一个新的问题`error Command failed with signal "SIGSEGV".`, 应用无法启动

**Comment by hyj1991** [comment]
这个应该和你的其它包有关系，easy-monitor 没有注册信号量

**Comment by amit-gshe** [comment]
我在node-12-lts-alpine镜像中, 采集cpu正常

**Comment by hyj1991** [comment]
所以现在是在哪个版本中有问题呢？我去看看能不能复现

**Comment by amit-gshe** [comment]
我现在也不能复现了, 也就是可以分析出来了, 不知道刚为什么无法分析出来, 但内存占用奇高, 初始容器内存占用只有200M不到, 分析完之后内存占用升到了2个G, 而且没有降回去.(环境: node:12-alpine镜像)

**Comment by hyj1991** [comment]
你执行的是内存分析么

**Comment by amit-gshe** [comment]
对, 内存分析

**Comment by hyj1991** [comment]
那是正常的，堆快照序列化反序列化 + 解析本来就吃内存

**Comment by hyj1991** [comment]
这里开启了一个子线程做分析处理，内存高也是系统的 swap，不影响你的业务进程

**Comment by amit-gshe** [comment]
不太确定是不是因为我用了ts-node的原因。当我使用ts-node运行项目时，这个插件无法使用，表现是cpu长时间100%，内存持续上升，前端一直在轮询分析结果，像是陷入了死循环。而当我将项目编译成js后使用node直接运行，就没有上面的问题，在分析内存的时候，虽然比较吃cpu和内存但整个过程不会太长就有结果。

**Comment by hyj1991** [comment]
ts 项目确实没尝试过，如果你有更多发现欢迎 pr :)
