### ISSUE TITLE
安装成功后CPU和MEN都不能用

### ISSUE THREAD

**Issue by JSMengLingqi** [hyj1991/easy-monitor#114]
![image](https://github.com/JSMengLingqi/photo_mlq/blob/master/1574755831.png)
![image](https://github.com/JSMengLingqi/photo_mlq/blob/master/1574755865(1).png)

**Comment by hyj1991** [comment]
图挂了，你启动的时候有错误日志么？

**Comment by JSMengLingqi** [comment]
> 图挂了，你启动的时候有错误日志么？

运行时log:
log: -------------------------------------swaggerSyncUtils constructor-----------------------------------------------
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v6.1.1/node-v57-win32-x64/profiler.node'
log: 服务已启动，请打开下面链接访问: 
http://127.0.0.1:3000/
log: mongodb load success...
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v6.1.1/node-v57-win32-x64/profiler.node'
[Easy-Monitor: dashboard <64616>] http_server start at 12333...
[Easy-Monitor: dashboard <64616>] tcp_server start at 26666...
[Easy-Monitor: embrace <53520>] connect to 127.0.0.1:26666 success...




点击CPU后log:
[Easy-Monitor: dashboard <64616>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: embrace <53520>] common.socket->onData error: TypeError: Cannot read property 'profilerP' of undefined
    at _start (E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_easy-monitor@2.2.7@easy-monitor\src_logic\embrace\controller\tcp.profiler.js:48:52)
    at _start.next (<anonymous>)
    at onFulfilled (E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_co@4.6.0@co\index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[Easy-Monitor: dashboard <64616>] common.socket->onData error: TypeError: Cannot read property 'composeKey' of undefined
    at _stat (E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_easy-monitor@2.2.7@easy-monitor\src_logic\dashboard\controller\tcp\tcp.stat.js:34:41)
    at _stat.next (<anonymous>)
    at onFulfilled (E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_co@4.6.0@co\index.js:65:19)
    at E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at co (E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_co@4.6.0@co\index.js:50:10)
    at controller.(anonymous function) (E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_easy-monitor@2.2.7@easy-monitor\src_logic\dashboard\controller\tcp\tcp.stat.js:20:16)
    at tmpArr.forEach.item (E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_easy-monitor@2.2.7@easy-monitor\src_logic\common\common.socket.js:102:67)
    at Array.forEach (<anonymous>)
    at Object.onData (E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_easy-monitor@2.2.7@easy-monitor\src_logic\common\common.socket.js:93:20)
[Easy-Monitor: dashboard <64616>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <64616>] http.axios.detail error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <64616>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined

**Comment by hyj1991** [comment]
> [Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v6.1.1/node-v57-win32-x64/profiler.node'

v8-profiler-node8 没有正确安装

**Comment by hyj1991** [comment]
编译出来的 addon 文件没有生成

**Comment by JSMengLingqi** [comment]
试了很多次npm install v8-profiler-node8。。。

E:\workspace\my-yapi-1.4.3\bxCrazyYapi>cnpm install v8-profiler-node8
√ Installed 1 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 193ms(network 190ms), speed 5.73kB/s, json 1(1.09kB), tarball 0B)

**Comment by hyj1991** [comment]
删掉 node_modules/v8-profiler-node8，然后再执行 install，windows 下需要自身编译，别的地方拷贝过来的是没法用的

**Comment by JSMengLingqi** [comment]
卡在这里不知道怎么办了。。。

**Comment by hyj1991** [comment]
`npm install` 只检测包的基本数据在不在，不会判断包完整不完整，你可以看下 `node_modules/v8-profiler-node8/build/profiler/v6.1.1/` 下肯定没有 `node-v57-win32-x64/profiler.node` 这个文件

**Comment by hyj1991** [comment]
卡在哪里？

**Comment by JSMengLingqi** [comment]
E:\workspace\my-yapi-1.4.3\bxCrazyYapi>npm install v8-profiler-node8
npm WARN checkPermissions Missing write access to E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\gauge\node_modules\strip-ansi
npm WARN checkPermissions Missing write access to E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\v8-profiler-node8
npm WARN checkPermissions Missing write access to E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\v8-profiler-node8\node_modules\nan
npm WARN checkPermissions Missing write access to E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\v8-profiler-node8\node_modules
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.0.3 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.

npm ERR! path E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\gauge\node_modules\strip-ansi
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\gauge\node_modules\strip-ansi'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\menglingqi\AppData\Roaming\npm-cache\_logs\2019-11-26T08_36_53_097Z-debug.log



上面是执行>npm install v8-profiler-node8的log

**Comment by hyj1991** [comment]
npm cache clean --force，然后再执行下 npm install

**Comment by JSMengLingqi** [comment]
npm cache clean --force后，执行cnpm install v8-profiler-node8，报错如下：

E:\workspace\my-yapi-1.4.3\bxCrazyYapi>cnpm install v8-profiler-node8
| [0/1] Installing v8-profiler-node8@*[npminstall:runscript] scripts.preinstall v8-profiler-node8@*  "node -e 'process.exit(0)'", root: "E:\\workspace\\my-yapi-1.4.3\\bxCrazyYapi\\node_modules\\_v8-profiler-node8@6.1.1@v8-profiler-node8"
√ Installed 1 packages
√ Linked 2 latest versions
[1/1] scripts.install v8-profiler-node8@* run "node-pre-gyp install --fallback-to-build", root: "E:\\workspace\\my-yapi-1.4.3\\bxCrazyYapi\\node_modules\\_v8-profiler-node8@6.1.1@v8-profiler-node8"

E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_v8-profiler-node8@6.1.1@v8-profiler-node8>"node"  "E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_v8-profiler-node8@6.1.1@v8-profiler-node8\node_modules\.bin\\..\..\..\_node-pre-gyp@0.13.0@node-pre-gyp\bin\node-pre-gyp" install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for v8-profiler-node8@6.1.1 and node@8.16.2 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error unable to verify the first certificate
gyp http GET https://npm.taobao.org/mirrors/node/v8.16.2/node-v8.16.2-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:643:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\node.exe" "E:\\workspace\\my-yapi-1.4.3\\bxCrazyYapi\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\workspace\\my-yapi-1.4.3\\bxCrazyYapi\\node_modules\\_v8-profiler-node8@6.1.1@v8-profiler-node8\\build\\profiler\\v6.1.1\\node-v57-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=E:\\workspace\\my-yapi-1.4.3\\bxCrazyYapi\\node_modules\\_v8-profiler-node8@6.1.1@v8-profiler-node8\\build\\profiler\\v6.1.1\\node-v57-win32-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_v8-profiler-node8@6.1.1@v8-profiler-node8
gyp ERR! node -v v8.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\Program Files (x86)\nodejs\node.exe E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_v8-profiler-node8@6.1.1@v8-profiler-node8\build\profiler\v6.1.1\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_v8-profiler-node8@6.1.1@v8-profiler-node8\build\profiler\v6.1.1\node-v57-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_node-pre-gyp@0.13.0@node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "D:\\Program Files (x86)\\nodejs\\node.exe" "E:\\workspace\\my-yapi-1.4.3\\bxCrazyYapi\\node_modules\\_node-pre-gyp@0.13.0@node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_v8-profiler-node8@6.1.1@v8-profiler-node8
node-pre-gyp ERR! node -v v8.16.2
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'D:\Program Files (x86)\nodejs\node.exe E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_v8-profiler-node8@6.1.1@v8-profiler-node8\build\profiler\v6.1.1\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=E:\workspace\my-yapi-1.4.3\bxCrazyYapi\node_modules\_v8-profiler-node8@6.1.1@v8-profiler-node8\build\profiler\v6.1.1\node-v57-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
[1/1] scripts.install v8-profiler-node8@* finished in 7s
√ Run 1 scripts
√ All packages installed (1 packages installed from npm registry, used 8s(network 890ms), speed 15.5kB/s, json 3(13.8kB), tarball 0B)

**Comment by hyj1991** [comment]
看下这个 https://blog.csdn.net/fclwd/article/details/79894251
你编译前下载 node.h 失败了，看起来是 ssl 没过

**Comment by JSMengLingqi** [comment]
按照连接中的方法都执行过了，仍是报上述错误。实际上从昨天到今天我就一直卡在这个错误过不去，很惆怅，不知道咋办。能查到的资料都查过试了，还是报这个错误。

**Comment by JSMengLingqi** [comment]
npm：6.13.1
node ：v8.16.2

**Comment by hyj1991** [comment]
我估计是你的 node 下载的有问题

不行你就访问 https://npm.taobao.org/mirrors/node/v8.16.2/node-v8.16.2-headers.tar.gz，把下载下来的 tar.gz 解压出来的 include 文件夹复制到 `C:\Users\你的用户名\.node-gyp\8.16.2` 下

**Comment by hyj1991** [comment]
本质上是 node-gyp 编译 addon 需要这些 include 文件夹下的头文件，所以你没有的话会走从远程的下载

**Comment by JSMengLingqi** [comment]
我的.node-gyp文件夹是空的，新建了一个8.16.2，然后将include 文件粘进去
执行npm install仍报上述错误，同时node-gyp文件夹被清空

**Comment by hyj1991** [comment]
那就不知道了，nvm 换个 node 版本试下吧

**Comment by JSMengLingqi** [comment]
昨天试了重新装node，还是不行。换了两台电脑试也不行。。哎好郁闷

**Comment by hyj1991** [comment]
不要用 cnpm，试下直接用 npm 呢

**Comment by JSMengLingqi** [comment]
会报一样的错

**Comment by hyj1991** [comment]
确实不知道怎么帮你解决这个问题，因为我身边没有 windows 的机器，今天购买了 parallel desktop15 安装了 win10 虚拟机，安装了 vs2017  和 python2.7 环境后，编译 v8-profiler-node8 没有遇到任何问题。。。

**Comment by JSMengLingqi** [comment]
> 确实不知道怎么帮你解决这个问题，因为我身边没有 windows 的机器，今天购买了 parallel desktop15 安装了 win10 虚拟机，安装了 vs2017 和 python2.7 环境后，编译 v8-profiler-node8 没有遇到任何问题。。。

vs2017是啥。。我装下试试

**Comment by hyj1991** [comment]
visual studio code 2017

**Comment by hyj1991** [comment]
先关闭了，有啥进展可以贴这里
