### ISSUE TITLE
[RFC] 2020 年计划完成 Easy-Monitor 3.0 版本的开发工作

### ISSUE THREAD

**Issue by hyj1991** [hyj1991/easy-monitor#117]
打造国内第一流的 Node.js 性能监控体系，让天下没有难用的 Node.js

**Comment by hyj1991** [comment]
整体设计架构图占位

**Comment by hyj1991** [comment]
Easy-Monitor 3.0 版本各个模块进展：
- [x] 实时 Runtime 内核日志输出与 profiling 指令接收插件：[xprofiler](https://github.com/hyj1991/xprofiler) 
- [ ] 插件日志采集中转与指令转换器：[xtransit](https://github.com/hyj1991/xtransit)

**Comment by hyj1991** [comment]
#121

**Comment by hyj1991** [comment]
#122

**Comment by cc4dogman** [comment]
能不能支持下nodejs10+

**Comment by hyj1991** [comment]
> 能不能支持下nodejs10+

10+ 不是一直都支持的么。

**Comment by cc4dogman** [comment]
10下面在centos6上有些静态包版本编译不过去~~现网老服务器不敢升级 蛋疼

**Comment by hyj1991** [comment]
> 10下面在centos6上有些静态包版本编译不过去~~现网老服务器不敢升级 蛋疼

项目本身是支持 Node-v10.x 的，不过依赖里有一个 addon，我估计是你的服务器上没有 gcc 编译环境吧。

**Comment by cc4dogman** [comment]
是的 这个除了换个机器部署没变的办法 老环境连docker都装不了

**Comment by hyj1991** [comment]
done.

**Comment by hyj1991** [comment]
landed on https://github.com/hyj1991/easy-monitor/commit/f16a8f07e30bdd3b0dc11ae5652cfdb772d3967a
