### ISSUE TITLE
火焰图底部出现两个调用名称为anonymous的

### ISSUE THREAD

**Issue by x363090973** [hyj1991/easy-monitor#118]
火焰图底部出现两个调用名称为anonymous的 ，是什么意思，为什么会导致这样的？

**Comment by hyj1991** [comment]
贴个图？

**Comment by x363090973** [comment]
@hyj1991  在线答疑太感动了...
模块中没有anonymous的函数，并且最上层的anonymous根据显示上面的函数名词 ，此anonymous函数名应该是output的,
![1](https://user-images.githubusercontent.com/32871542/74897772-14c6d000-53d3-11ea-8e90-79e016d036d7.png)

**Comment by hyj1991** [comment]
anonymous 就是匿名函数的意思，你的代码中肯定不会有 `anonymous ` 字样，比如:

```js
http.request('http://www.baidu.com', function(res) {});
```

这里给 `http.request` 方法设置的回调函数就是匿名函数，相对而言，如果这样写:

```js
http.request('http://www.baidu.com', function test(res) {});
```

那这个函数的 name 就是 `test`，不是匿名的了。

你图中的两个匿名函数，显然是 runtime 内部的调用，最下面一层是 v8 的 microtasks 了，你在火焰图中只需要关注你的业务相关函数即可。

**Comment by hyj1991** [comment]
没有其它疑问这个 issue 我关闭了，如果还有其它问题可以再打开他讨论

**Comment by x363090973** [comment]
Thanks♪(･ω･)ﾉ,工具挺好用的,解决我的实际问题，我向朋友安利了

**Comment by hyj1991** [comment]
正在做 Easy-Monitor 3.0 的版本，会有非常大的更新，加入了团队协作等更加适合企业本地部署的内容，欢迎关注 :)
