### ISSUE TITLE
cpu采集完毕之后，无法生成cpu的分析报告

### ISSUE THREAD

**Issue by x363090973** [hyj1991/easy-monitor#119]
node:10.13.0 
windows,
easy-monitor:^2.2.7

<--- Last few GCs --->

<--- JS stacktrace --->

#
# Fatal process OOM in insufficient memory to create an Isolate
#

[Easy-Monitor: embrace <12028>] tcp.profiler calculate failed with exit code 3221225477!
[Easy-Monitor: embrace <12028>] common.socket->onData error: undefined

**Comment by hyj1991** [comment]
> https://github.com/hyj1991/easy-monitor/blob/master/src_logic/embrace/controller/tcp.profiler.js#L48

加个日志把这里生成的 `profiler` 打印出来看下呢？
如果是字符串的话，直接写到文件，传到这里我看下

**Comment by x363090973** [comment]
[profiler.txt](https://github.com/hyj1991/easy-monitor/files/4347876/profiler.txt)
这里

**Comment by hyj1991** [comment]
这是一个正常的 cpuprofile，你可以先传到 chrome-devtools 里面看下（需要把文件后缀改为 .cpuprofile），看你这边的错误是解析的时候内存溢出了，我回去了看下具体原因

**Comment by x363090973** [comment]
嗯，我吧node降到了V8就正常了

**Comment by hyj1991** [comment]
出问题的你用的是哪个版本，我今天看下这个问题

**Comment by x363090973** [comment]
10.13.0

**Comment by hyj1991** [comment]
![image](https://user-images.githubusercontent.com/19908330/77068071-f202f800-6a20-11ea-9813-1a8fc0ef8cf2.png)
我用 Node.js-v10.13.0，测试了下你发的这个 cpuprofile 的解析貌似没啥问题

**Comment by hyj1991** [comment]
我是直接替换了需要解析的 cpuprofile 文件为你发我的这个 profier.txt，因为你抛错的地方实际上是分析生成的 cpuprofile 文件的子进程 OOM 了，但是这里测试了看了并不会。

最好你能提交一个最小可复现的仓库，我这边可以进一步跟进下这个问题。

**Comment by x363090973** [comment]
嗯 我本地再复现一下试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hyj1991"<notifications@github.com&gt;; 
发送时间: 2020年3月19日(星期四) 晚上8:39
收件人: "hyj1991/easy-monitor"<easy-monitor@noreply.github.com&gt;; 
抄送: "363090973"<363090973@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hyj1991/easy-monitor] cpu采集完毕之后，无法生成cpu的分析报告 (#119)





 
我是直接替换了需要解析的 cpuprofile 文件为你发我的这个 profier.txt，因为你抛错的地方实际上是分析生成的 cpuprofile 文件的子进程 OOM 了，但是这里测试了看了并不会。
 
最好你能提交一个最小可复现的仓库，我这边可以进一步跟进下这个问题。

**Comment by x363090973** [comment]
我本地跑了一下，10.13.0 64 位正常，出错的是我的 32位的node版本，当时因一个项目的需要开发期间用了这个版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hyj1991"<notifications@github.com&gt;; 
发送时间: 2020年3月19日(星期四) 晚上8:39
收件人: "hyj1991/easy-monitor"<easy-monitor@noreply.github.com&gt;; 
抄送: "363090973"<363090973@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hyj1991/easy-monitor] cpu采集完毕之后，无法生成cpu的分析报告 (#119)





 
我是直接替换了需要解析的 cpuprofile 文件为你发我的这个 profier.txt，因为你抛错的地方实际上是分析生成的 cpuprofile 文件的子进程 OOM 了，但是这里测试了看了并不会。
 
最好你能提交一个最小可复现的仓库，我这边可以进一步跟进下这个问题。

**Comment by hyj1991** [comment]
@x363090973 这条消息竟然没有推送到，32 位上 heap 限制只有 700M，确实有可能会存在内存溢出的情况，不过现在基本上服务器都是 64 位的了

这个 issue 我先关闭，回头我研究下 32 位下解析为什么会消耗这么大的空间。
