### ISSUE TITLE
关于monitor 在pm2的cluster模式下运行如何保证只运行单个monitor服务

### ISSUE THREAD

**Issue by liSong5713** [hyj1991/easy-monitor#120]

**Comment by hyj1991** [comment]
具体是什么问题？

**Comment by liSong5713** [comment]
sorry 我这边一下操作错了。再重新编辑

**Comment by hyj1991** [comment]
如果是单机的话，现在默认就是 dashboard 竞争端口只会成功启动一个。

如果你指的是集群部署的话，参考这个 http://47.100.164.242/document/#/?id=-cluser-%e6%a8%a1%e5%bc%8f

**Comment by hyj1991** [comment]
先关闭了，如果还有其他问题可以再打开继续在这里讨论。
