### ISSUE TITLE
heroku 使用問題

### ISSUE THREAD

**Issue by zeteticl** [hyj1991/easy-monitor#123]
我在HEROKU作為使用環境, 但heroku好像只能使用port 80
可以怎解決問題....?

**Comment by hyj1991** [comment]
不太理解你的问题，也许你指的是 [虚拟路径转发](http://120.27.24.200/easy-monitor/document#/?id=-%e8%99%9a%e6%8b%9f%e8%b7%af%e5%be%84%e8%bd%ac%e5%8f%91)?

**Comment by hyj1991** [comment]
如果没有其它问题此 issue 我先关闭了 :)
