### ISSUE TITLE
启动后报错，请帮忙看一下，谢谢

### ISSUE THREAD

**Issue by lchan243** [hyj1991/easy-monitor#125]
监控页面可以正常访问了，但是应用启动的过程中，看到有如下的异常，这个需要如何解决？ 
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v6.2.0/node-v64-darwin-x64/profiler.node'

**Comment by hyj1991** [comment]
看 electron 的文档: https://www.electronjs.org/docs/tutorial/using-native-node-modules
