### ISSUE TITLE
将easymonitor接入到了一款聊天应用里面，启动内存和cpu分析的时候，tcp连接会被关掉，我的应用也会自动退出

### ISSUE THREAD

**Issue by lchan243** [hyj1991/easy-monitor#126]
如下异常：
[Easy-Monitor: dashboard <67314>] tcpserver->error Error: read ECONNRESET

是不是跟聊天应用本身的通信机制会有冲突呢？

**Comment by hyj1991** [comment]
最好提供一个能复现的代码，正常来说是不会有问题的。

**Comment by lchan243** [comment]
代码没有什么特别的地方，就是用的electron框架，然后在主进程的入口require了，启动的过程没有报错。解析os的功能是OK的，选择cpu和内存进行解析的时候，就出现我标题发的那个异常现象了

**Comment by hyj1991** [comment]
> 代码没有什么特别的地方，就是用的electron框架，然后在主进程的入口require了，启动的过程没有报错。解析os的功能是OK的，选择cpu和内存进行解析的时候，就出现我标题发的那个异常现象了

有一个可能是你没有正确编译出来 electron 对应的 v8-profiler-node8 这个 addon，导致加载异常的动态链接库的时候直接 render process crash 了

**Comment by hyj1991** [comment]
所以表象看起来就像是影响到你的通信逻辑。

**Comment by lchan243** [comment]
> > 代码没有什么特别的地方，就是用的electron框架，然后在主进程的入口require了，启动的过程没有报错。解析os的功能是OK的，选择cpu和内存进行解析的时候，就出现我标题发的那个异常现象了
> 
> 有一个可能是你没有正确编译出来 electron 对应的 v8-profiler-node8 这个 addon，导致加载异常的动态链接库的时候直接 render process crash 了

我从这个方向再研究一下，thx

**Comment by lchan243** [comment]
> > 代码没有什么特别的地方，就是用的electron框架，然后在主进程的入口require了，启动的过程没有报错。解析os的功能是OK的，选择cpu和内存进行解析的时候，就出现我标题发的那个异常现象了
> 
> 有一个可能是你没有正确编译出来 electron 对应的 v8-profiler-node8 这个 addon，导致加载异常的动态链接库的时候直接 render process crash 了

应该是你说的问题了，我重新在工程里面安装了一下v8-profiler-node8，有个warning，之前没注意到，看起来是没找到对应的。
Pre-built binaries not found for v8-profiler-node8@6.2.0 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by hyj1991** [comment]
这个 warning 是正常的，接下来会 fallback 到 local compile，下面有报错么

**Comment by lchan243** [comment]
我重新安装了之后，再启动就OK了。。。谢谢了～
再多问一个问题，如果我在这个项目里的主进程和渲染进程都require，会有冲突吗？这两个都会有负载

**Comment by hyj1991** [comment]
> 我重新安装了之后，再启动就OK了。。。谢谢了～
> 再多问一个问题，如果我在这个项目里的主进程和渲染进程都require，会有冲突吗？这两个都会有负载

不会冲突，做了处理了。

那这个 issue 我关闭了
