### ISSUE TITLE
dashboard支持socket进程吗v2

### ISSUE THREAD

**Issue by lifefloating** [hyj1991/easy-monitor#127]

**Comment by hyj1991** [comment]
没看懂，支持 socket 进程指的是？

**Comment by lifefloating** [comment]
/*dashboard: {
        port_http: 20000,
        port_tcp: 30000
    }*/

有些服务我并没有指定端口
unix  3      [ ]         STREAM     CONNECTED     197360925 10472/node
类似这种 我想不指定端口，通过进程号可行吗

**Comment by hyj1991** [comment]
这个暂时不行，client 和 dashboard 之间的通信现在走的是 tcp，没有支持本机下的 domain socket 通信

**Comment by lifefloating** [comment]
好的，谢谢大佬，那我还是通过指定端口这种方式吧

**Comment by hyj1991** [comment]
嗯，即将发布的 3.0 版本会覆盖更多的场景，应该可以满足你的这个需求
