### ISSUE TITLE
k8s支持

### ISSUE THREAD

**Issue by NetFilx** [hyj1991/easy-monitor#128]
配置了k8s的路由之后存在无法访问的问题

**Comment by NetFilx** [comment]
整个页面直接白屏了

**Comment by hyj1991** [comment]
白屏是静态资源没有正确加载导致页面没有正常生成，看下是不是要配置虚拟转发路径: http://120.27.24.200/easy-monitor/document#/?id=-%e8%99%9a%e6%8b%9f%e8%b7%af%e5%be%84%e8%bd%ac%e5%8f%91

**Comment by NetFilx** [comment]
配置了虚拟路径转发，本地启动没有问题，看了一下本地的控制台：
![image](https://user-images.githubusercontent.com/23232348/82183989-7edf0a80-9919-11ea-9834-c9deaceb0048.png)
看了一下线上的控制台，发现少加载一些东西：
![image](https://user-images.githubusercontent.com/23232348/82184073-9e763300-9919-11ea-8c09-898fe0a693b5.png)
发现有一个叫做2.chunk.js的文件没有加载，但是我直接访问这个文件就是可以访问到的

**Comment by hyj1991** [comment]
这个就是静态资源配置路径有问题，你是怎么配置 k8s 上的转发规则的？

**Comment by hyj1991** [comment]
而且你的访问路径里为啥有两个 `/monitor` ?

**Comment by NetFilx** [comment]
![image](https://user-images.githubusercontent.com/23232348/82184664-95d22c80-991a-11ea-9b69-37fc5604802d.png)
这个是我代码的配置
![image](https://user-images.githubusercontent.com/23232348/82184784-c3b77100-991a-11ea-87fc-0b5f8ca3afd8.png)
这个是我的k8s配置

**Comment by NetFilx** [comment]
我发现我配置了虚拟路径转发之后就存在这个问题，需要两个才行

**Comment by hyj1991** [comment]
访问下 `/monitor/index` 看看

**Comment by NetFilx** [comment]
一样的效果，还是白屏

**Comment by hyj1991** [comment]
这个就是路径的问题，我对 k8s 的转发规则配置不熟悉，你需要配置达到的效果就是把所有 `/monitor` 开头的路由完整转发到 k8s 内的 `http://127.0.0.1:12333` 下，比如：

`http://api-dev.xxx/easy-monitor/index` 要转发为 `http://127.0.0.1:12333/easy-monitor/index`，

达到这个目的，应该就可以访问了

**Comment by NetFilx** [comment]
行吧 我再试试

**Comment by NetFilx** [comment]
谢谢啦

**Comment by hyj1991** [comment]
不客气
