### ISSUE TITLE
mem分析占用时间特别长

### ISSUE THREAD

**Issue by NetFilx** [hyj1991/easy-monitor#129]
![image](https://user-images.githubusercontent.com/23232348/82279414-18142c80-99bf-11ea-9a89-5eb2bc8d9075.png)
停留在这个页面差不多有半个小时了，如何解决？

**Comment by hyj1991** [comment]
看看服务器日志上有没有报错信息

**Comment by NetFilx** [comment]
这个日志打在哪里？有专门的目录吗？没看到文档中有提及

**Comment by hyj1991** [comment]
你的应用里

**Comment by NetFilx** [comment]
好的 我先看看

**Comment by NetFilx** [comment]
没有看到相关的日志

**Comment by hyj1991** [comment]
看你应用的 stdout/stderr 日志有没有信息。

**Comment by NetFilx** [comment]
还是没有看到错误信息

**Comment by hyj1991** [comment]
那就不知道了，正常分析不会这么久，如果你有复现的办法也可以贴代码我看下，只有这个界面没办法看到是什么问题

**Comment by NetFilx** [comment]
行吧，我再看看好啦，3q
