### ISSUE TITLE
调用的时候报错？

### ISSUE THREAD

**Issue by hulkhub** [hyj1991/easy-monitor#13]
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v5.7.6/node-v48-win32-x64/profiler.node'

**Comment by hyj1991** [comment]
@hulkhub 这个错误是安装 v8-profiler 的时候没有成功，删除重新 npm install 一下看看
正常来说 node-v48-win32-x64 的包官方有编译好的 windows 平台下的可以直接下载，估计是你的网络获取编译好的包的时候出错，然后走了 ```node-gyp rebuild``` 重新编译了，但是编译失败

**Comment by hulkhub** [comment]
@hyj1991问题已解决，thk...

**Comment by hyj1991** [comment]
@hulkhub ok~
