### ISSUE TITLE
想问下大佬xprofiler-console 视图层有无考虑开源呢？

### ISSUE THREAD

**Issue by kekobin** [hyj1991/easy-monitor#132]
一开始考虑alinode，不过因为公司不允许数据上报到第三方平台，所以后来只能自己封装告警模块、上报模块，兜底告警加上报，算是简陋版的监控方案吧。知道看到easy-monitor，真的是眼前一亮呀。太好用了也，感觉真的达到了作者所说的“让天下没有难用的nodejs”。不过还是有个缺憾，xprofiler-console的视图部分不知道有否考虑开源，因为私有化部署，就会有相对应的私有化视图定制的需求。目前在准备内部搭建一套，很感谢作者无私的开源精神！

**Comment by hyj1991** [comment]
目前视图层不考虑开源，因为国内拿去改几个字拿开源项目去卖钱的情况太多了。
目前开放出来的部分已经足够私有化部署使用了

**Comment by kekobin** [comment]
> 目前视图层不考虑开源，因为国内拿去改几个字拿开源项目去卖钱的情况太多了。
> 目前开放出来的部分已经足够私有化部署使用了

不过确实国内是有很不好的这种风气，不尊重开源作者的成果。
