### ISSUE TITLE
xtransit-manager和 xtransit-server 访问报错

### ISSUE THREAD

**Issue by liumengniu** [hyj1991/easy-monitor#136]
版本：ESZ3.0
环境：win10
xtransit-manager 一旦访问服务，就报如下错误
![image](https://user-images.githubusercontent.com/24428623/85243201-c2c2b380-b473-11ea-9381-1c1031e116bb.png)
xtransit-serve 一旦访问服务，就报错误 client shutdown: appId not exists
我已反复验证 appId 和 appSecret 配置无误，之前的项目同样的配置是可以的，大概两天前拉取的项目出现的问题

**Comment by liumengniu** [comment]
这是配置文件
![image](https://user-images.githubusercontent.com/24428623/85243480-8fccef80-b474-11ea-8d20-5c2f03b09e86.png)
这是项目内启动步骤
![image](https://user-images.githubusercontent.com/24428623/85243513-a70bdd00-b474-11ea-837f-8730f9151d0a.png)

**Comment by hyj1991** [comment]
> https://github.com/X-Profiler/xtransit-server/blob/master/handler/message.js#L31

这行报的错误，实际上就是你的 xtransit 连接到 xtransit-server 的时候会去 manager 查找上报的 appId 对应的信息，这里是没有获取到

**Comment by hyj1991** [comment]
你可以根据这里的代码跟踪下，为啥这里的 appId 3 没有获取到对应的 secret 信息

**Comment by liumengniu** [comment]
![image](https://user-images.githubusercontent.com/24428623/85243989-f43c7e80-b475-11ea-83c5-7521c5577eff.png)
我正在追溯，只是效率不高（不熟悉），应该是哪个地方 JSON.parse取 ID和secret 的时候报错了

**Comment by hyj1991** [comment]
> https://github.com/X-Profiler/xtransit-manager/blob/master/app/controller/xtransit.js#L6

看到了这个 congtroller 了没，另外不要用 node-v14.x，http 底层改了目前 egg 依赖的几个模块有兼容性问题

**Comment by liumengniu** [comment]
hello，我只能大概定位到了  xtransit-server的错误，断在了这个地方
![image](https://user-images.githubusercontent.com/24428623/85245356-e0931700-b479-11ea-8f64-ae3dfcf612e4.png)
data 不是json 数据，xtransit-manager还没找到原因

**Comment by liumengniu** [comment]
xtransit-manager 也 全部解决了，谢谢

**Comment by liumengniu** [comment]
总结一下win10 遇到的问题
1、我习惯和 开源作者使用同一版本的第三方依赖（担心出幺蛾子），但是xtransit-manager 的现在依赖版本有点小问题（多次删除node_modules重新安装也不行） ，详见https://github.com/eggjs/egg/issues/3457， 还原了 "^"，拉取最新版本则OK
2、win 系统在 xtransit-server 需要使用 cross-env 启动开发服务
![image](https://user-images.githubusercontent.com/24428623/85247003-fc4cec00-b47e-11ea-8c67-bdc99fb9c368.png)

**Comment by hyj1991** [comment]
启动命令那块来个 pr？

**Comment by liumengniu** [comment]
提了个pr，单开了个dev-win 的命令

**Comment by hyj1991** [comment]
> 提了个pr，单开了个dev-win 的命令

done
