### ISSUE TITLE
easy-monitor2内存分析页面卡主

### ISSUE THREAD

**Issue by zoumz** [hyj1991/easy-monitor#139]
在本地跑的时候，发现内存分析这个页面会卡主，

一直显示下面这句话
Real Nodes 读取完毕, 耗时 3.36 s, 准备开始将 Ordinal ID 转换为 Real ID......

请问下大佬，本地跑的时候，还需要额外做什么配置吗~~~

**Comment by hyj1991** [comment]
不需要，用 3.0 版本

**Comment by zoumz** [comment]
好的，谢谢大佬，想知道为啥在2.0这个版本会出现这个问题~~~
