### ISSUE TITLE
egg的run debug下调用报错，child_process exit with code 12...

### ISSUE THREAD

**Issue by liuyu322** [hyj1991/easy-monitor#14]
![image](https://user-images.githubusercontent.com/5425933/27626329-36c05b4e-5c1a-11e7-802a-b8eaf0c6ad21.png)
这是什么原因？

**Comment by hyj1991** [comment]
@liuyu322 参看这个 [issue#10](https://github.com/hyj1991/easy-monitor/issues/10)

**Comment by liuyu322** [comment]
@hyj1991 必须给个赞👍

**Comment by hyj1991** [comment]
已解决
