### ISSUE TITLE
文档打不开

### ISSUE THREAD

**Issue by zoumz** [hyj1991/easy-monitor#140]
https://github.com/hyj1991/easy-monitor/tree/v2.x
————————————————————————————
文档中的第三部分
III. 深度定制化 & 通用配置 &动态更新配置
深度定制化开发、通用配置项以及如何动态更新配置项详见 **Easy-Monitor 详细文档**文档链接打不开

https://cnodejs.org/topic/594f6e21642874f845d9fe0d#599beae0bae6f2ed6f7e4c45
此文中的更多关于 集群部署、深度定制化开发、通用配置以及动态更新配置的说明可以查看 Easy-Monitor 详细文档 。文档链接也打不开
——————————————————————————————
大佬，是不维护这部分文档了么~~~

**Comment by hyj1991** [comment]
2.x 不维护了

**Comment by zoumz** [comment]
> 2.x 不维护了

好的，谢谢大佬，看到集群 C/S 部署 dashboard 进程，这块的时候，有点蒙，所以想找文档看看~~~

**Comment by hyj1991** [comment]
@zoumz 但是文档内容还在，你可以直接看 https://github.com/hyj1991/easy-monitor/tree/v2.x/src_logic/dashboard/public/document
