### ISSUE TITLE
压测处理时，QPS坐标轴有问题

### ISSUE THREAD

**Issue by kekobin** [hyj1991/easy-monitor#141]
大佬，我在压测时，QPS坐标轴展示如下：
![image](https://user-images.githubusercontent.com/4536310/97800069-0e306e00-1c6d-11eb-9411-5f9afa87e9cc.png)

很明显，纵坐标qps已经乱了，且实际的最大QPS已经将近1.8w，坐标轴的上线才7K多。这里是不是有问题

**Comment by kekobin** [comment]
找个问题了，是数值上万后，charts宽度不够，将万位数字截掉了

**Comment by hyj1991** [comment]
是的，这里的图表是我基于 svg 自己封装的，没有用开源的那些图表库。。。存在一些 bug，这里我修下

**Comment by hyj1991** [comment]
已经修复: https://github.com/X-Profiler/xprofiler-console/commit/ed1cbfc20682544354aa1b1b79f28fbf34f27754

更新下 `xprofiler-console` 即可
