### ISSUE TITLE
按照文档配置完之后显示插件配置错误

### ISSUE THREAD

**Issue by vius** [hyj1991/easy-monitor#144]

**Comment by hyj1991** [comment]
哪里打 x 改哪里

**Comment by vius** [comment]
![Uploading image.png…]()

**Comment by vius** [comment]
> 哪里打 x 改哪里

插件 X-Profiler 状态：
已安装
未启用
日志目录配置失败

我在业务代码里 调用了  xprofiler.start() 这不是已经启动了吗？

**Comment by hyj1991** [comment]
> > 哪里打 x 改哪里
> 
> 插件 X-Profiler 状态：
> 已安装
> 未启用
> 日志目录配置失败
> 
> 我在业务代码里 调用了 xprofiler.start() 这不是已经启动了吗？

你检查的进程 pid 就是你启动 xprofiler 的进程？

**Comment by vius** [comment]
> > > 哪里打 x 改哪里
> > 
> > 
> > 插件 X-Profiler 状态：
> > 已安装
> > 未启用
> > 日志目录配置失败
> > 我在业务代码里 调用了 xprofiler.start() 这不是已经启动了吗？
> 
> 你检查的进程 pid 就是你启动 xprofiler 的进程？
是的 
业务代码：
xtransit start ./config.js xtransit has started(pid: 24867)
控制台信息：
1. 插件 X-Profiler 状态：
已安装
未启用
日志目录配置失败
2. 插件 X-Profiler 配置：
无法获取配置
3. 进程 24867 使用的运行时版本为 v14.15.0
都是24867
