### ISSUE TITLE
egg 项目config  中的xtransit 设置的server :'ws://127.0.0.1:9090' 这个服务有什么作用?

### ISSUE THREAD

**Issue by liSong5713** [hyj1991/easy-monitor#149]
环境：macos |  nodejs 14.17  | xprofiler-console@1.0.0 

如题：我按照文档中 《Node.js 应用接入（Egg.js）》流程启动了xprofiler-console,  但是在启动egg client端 发现没找到 ws://127.0.0.1:9090这个服务？ 请问该服务也至于xprofiler-console中吗？如果在的话默认端口是多少？

**Comment by liSong5713** [comment]
我的疏忽 未往下看到xtransit-manager的部署，抱歉打扰！

**Comment by hyj1991** [comment]
> 我的疏忽 未往下看到xtransit-manager的部署，抱歉打扰！

哈哈，照着文档来一遍准能跑起来
