### ISSUE TITLE
为啥会这样啊

### ISSUE THREAD

**Issue by LmonZero** [hyj1991/easy-monitor#152]
![image](https://user-images.githubusercontent.com/56548943/148670233-92d34481-5589-42b9-ac31-25e564536c85.png)
![image](https://user-images.githubusercontent.com/56548943/148670242-1425f1fb-30aa-4e97-8875-68973ec7fa4c.png)

**Comment by hyj1991** [comment]
启动的 nodejs 版本要和 install 的 nodejs 版本保持一致。
