### ISSUE TITLE
部署报错，version 'GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by beforegolive** [hyj1991/easy-monitor#157]
尝试在公司内网使用xprofiler，部署时报错，如标题。
连到docker镜像里，列了一下此组件的信息，发现版本只支持到到GLIBCXX_3.4.19。

docker内的系统是centos 7，试着升级组件libstdc++，未成功。

请问，有没有碰过此类问题？建议的解决方案是什么？

**Comment by hyj1991** [comment]
你用的是哪个 Node 版本？

**Comment by hyj1991** [comment]
你可以升级下 gcc，这里的编译工具链基本都是用的 devtoolset-6 / 8 了

**Comment by hyj1991** [comment]
先关闭了，如果有其它问题，欢迎继续回复讨论

**Comment by beforegolive** [comment]
你好，我直接升级了libstdc++.so.6解决了这个问题，但碰到了另外的问题。

测试环境里，我把每个环境部署好后，console控制那边看不到数据，不知道该怎么定位。

我弄了一个demo项目，内含一个接口，没有逻辑，直接返回字符串。主入口文件第一行也加了下面代码采集数据：
require('xprofiler').start()

引用的xtransit插件配置如下：

<img width="829" alt="image" src="https://user-images.githubusercontent.com/1415446/195293861-fb6dd27f-baa1-485c-a16e-46cccc4d2997.png">


服务器端方面分别部署了server、manager和console。

demo项目每次启动时，server那边会写入一条下面这样的日志，然后就没有动静了。
ERROR 52 [-/127.0.0.1/-/2397171ms GET /] client [1, demo-node-first-server-xxxxxxxxxx-xxx, xxxxxxx2342342343242xxx] has been closed.

我尝试用ws工具直连server是能捕捉到对应的日志信息的。

目前，控制台那边看不到对应的实例信息，日志这边只能查到这一步，然后就不知道该怎么办了。

请问，在部署的easy-monitor的过程中，有没有好的调试和定位问题的办法？

**Comment by beforegolive** [comment]
补充：在manager的服务器里有下面这样的日志，会请求server服务IP的9090端口，奇怪，我明明在npm start时通过--port把所有端口都改成80了，为啥还有9090端口？

![image](https://user-images.githubusercontent.com/1415446/195301112-7a13a429-8e4d-418e-8346-8a25901e0d36.png)

**Comment by hyj1991** [comment]
> 补充：在manager的服务器里有下面这样的日志，会请求server服务IP的9090端口，奇怪，我明明在npm start时通过--port把所有端口都改成80了，为啥还有9090端口？
> 
> ![image](https://user-images.githubusercontent.com/1415446/195301966-24a363e0-0458-40f6-96c3-89526141ffe3.png)

更新下 xtransit-server 的代码到最新试试，之前端口是通过读取配置设置进 redis 的，最新的版本修改成从 server info 中获取

**Comment by hyj1991** [comment]
参考这个：https://github.com/X-Profiler/xtransit-server/blob/master/app/service/manager.js#L50

**Comment by beforegolive** [comment]
拿了xtransit-server最新的代码并部署后，依然不行，manager服务的日志报错出现了陌生的IP和端口。
其中160后缀和119后缀的IP跟我部署的服务器匹配不上不说，端口出现了40969，这是为啥？
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/1415446/195499418-3d946c5e-937e-485f-8397-73394276dc7d.png">

**Comment by beforegolive** [comment]
找到原因！
egg-scripts start启动时需要指定参数 --daemon，这样端口设置才会生效，不然cluster端口会随机生成一个。

easy-monitor终于跑起来啦 ^_^

多谢帮忙。
