### ISSUE TITLE
【部署相关】EZM 对 MySQL+ Redis 的配置要求

### ISSUE THREAD

**Issue by kongfu-cat** [hyj1991/easy-monitor#158]
大佬，近期准备部署下 EZM，但帮助文档中并没有看到关于 MySQL 和 Redis 的具体的配置要求

**MySQL**

看文档中有说

> MySQL 的日志数据会定期清理，默认保留 7 天，200G 数据盘约能承载 2000 个实例的接入

也就是说一个接入的实例，走默认配置的话，7 天的日志数据就是 100MB 左右
假设我有 100 个实例，那么理论上应该使用配置为 10G ？其 QPS 是？

**Redis**

对于 Redis 的配置需求，目前没看到有地方描述。其 QPS 与内存使用大概是多少？
假设100个实例，大概需要怎样的配置

**Comment by hyj1991** [comment]
100 个实例，准备 50G Mysql 数据盘，2C 4G 的 Redis 足够了

**Comment by kongfu-cat** [comment]
好的，感谢

**Comment by hyj1991** [comment]
那我先关闭 issue 了，有其他问题可以加钉钉群咨询。
