### ISSUE TITLE
common.socket->onData error

### ISSUE THREAD

**Issue by nagisa3000** [hyj1991/easy-monitor#17]
用MEM检查内存的时候，浏览器会卡在“Memory Stream 准备完毕，即将开启子进程进行流式读取，此过程较慢，请耐心等待...”，cmd报错common.socket->onData error: TypeError: Cannot read property 'on' of null。
请问这个问题该怎么排查。

**Comment by hyj1991** [comment]
@nagisa3000 我看看本地能不能复现，感谢提供错误信息，如果有更多的错误信息可以在这里回复~

**Comment by nagisa3000** [comment]
@hyj1991 我用的是64位Win7 在我的机子上是必现的错误。

**Comment by hyj1991** [comment]
@nagisa3000 我晚上找台 Win7 64 位 的机器测试一下，结果在这里反馈

**Comment by nagisa3000** [comment]
[Easy-Monitor: dashboard <7664>] http_server start at 12333...
[Easy-Monitor: dashboard <7664>] tcp_server start at 26666...
[2017-07-04 15:21:59.147] [INFO] console - [Easy-Monitor: embrace <7888>] connect to 127.0.0.1:26666 success...
[2017-07-04 15:22:05.689] [INFO] console - [Easy-Monitor: embrace <7888>] common.socket->onData error: TypeError: Cannot read property 'on' of null
    at ExportStream.Readable.pipe (_stream_readable.js:507:7)
    at ChildProcess._innerSend [as innerSend] (E:\dev_server\node_modules\easy-monitor\src_logic\common\common.calculate.js:17:17)
    at _start (E:\dev_server\node_modules\easy-monitor\src_logic\embrace\controller\tcp.profiler.js:74:21)
    at next (native)
    at onFulfilled (E:\dev_server\node_modules\co\index.js:65:19)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

--------------------------------------

@hyj1991 错误信息如上 顺带我用的node版本是6.2.0

**Comment by hyj1991** [comment]
@nagisa3000 好的，这是比较关键的信息，我先下载 Node 6.2 看看能不能复现

**Comment by hyj1991** [comment]
@nagisa3000 找到原因了,是 Node 核心模块 child_process.js 升级过程中对于 fork 子进程时传入的 **stdio** 参数版本没有向下兼容导致的:

* 在 **Node v6.4.0** 之前，不支持在 fork 子进程时配置 **stdio** 参数

原始代码如下：
```js
options.stdio = options.silent ? ['pipe', 'pipe', 'pipe', 'ipc'] :
      [0, 1, 2, 'ipc'];
```

从 v6.4.0 开始后支持配置 stdio 参数，代码更改为:

```js
if (!Array.isArray(options.stdio)) {
    // Leave stdin open for the IPC channel. stdout and stderr should be the
    // same as the parent's if silent isn't set.
    options.stdio = options.silent ? ['pipe', 'pipe', 'pipe', 'ipc'] :
        [0, 1, 2, 'ipc'];
  } else if (options.stdio.indexOf('ipc') === -1) {
    throw new TypeError('Forked processes must have an IPC channel');
  }
```

而在 Easy-Monitor v2.1.2 中开启子进程进行负载的逻辑计算，因为只使用到了 stdin 流传输数据，所以仅设置了 stdin 流为管道类型:

```js
function fork(cpath, params) {
        //取出公共部分
        const config = this.config;
        const common = this.common;
        const dbl = this.dbl;

        //fork 进程，stdio 设置子进程的 stdin 为 pipe 备用传输数据，其余默认
        params = typeof params === 'string' && params || params && JSON.stringify(params) || '';
        const ps = cp.fork(cpath, [params], { stdio: ['pipe', 1, 2, 'ipc'], silent: false, execArgv: [] });
        //设置子进程内部方法
        ps.innerSend = _innerSend;

        return ps;
    }
```

这部分代码显然在 Node v6.4.0 之前时 stdio 参数设置无法生效，所以会报这个错误。

**临时解决方案**：

更改 **node_modules/easy-monitor/src_logic/common/common.calculate.js** 的 **38** 行，从：

```js
const ps = cp.fork(cpath, [params], { stdio: ['pipe', 1, 2, 'ipc'], silent: false, execArgv: [] });
```

更改为:

```js
const ps = cp.fork(cpath, [params], { stdio: ['pipe', 1, 2, 'ipc'], silent: true, execArgv: [] });
```

参考列表：
[CHANGELOG_V6.md#6.2.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.2.0)
[child_process: support stdio option in fork()](https://github.com/nodejs/node/pull/7811)

**Comment by nagisa3000** [comment]
@hyj1991 修改后可以正常执行了。十分感谢~

**Comment by hyj1991** [comment]
@nagisa3000 好的，不客气，感谢提供有用的信息反馈~

**Comment by hyj1991** [comment]
@nagisa3000 

Hi，这个问题已经修复: [commit#f00c00421cf5bb6421730fcfd41a1cbf443a94c4](https://github.com/hyj1991/easy-monitor/commit/f00c00421cf5bb6421730fcfd41a1cbf443a94c4)

下个版本合并

**Comment by nagisa3000** [comment]
@hyj1991 嗯嗯好的

**Comment by nagisa3000** [comment]
@hyj1991 还有一个问题，支持node 0.10.xx版本吗

**Comment by hyj1991** [comment]
@ nagisa3000 暂时没有这个计划，因为这个版本太古老了，在 IO.js 分裂之前了

2017-07-05 10:39 GMT+08:00 nagisa3000 <notifications@github.com>:

**Comment by nagisa3000** [comment]
@hyj1991 嗯嗯 确实太古老了
