### ISSUE TITLE
选择cpu + 子进程 无法进入分析页面。

### ISSUE THREAD

**Issue by Ali1213** [hyj1991/easy-monitor#19]
选择cpu + 子进程 无法进入分析页面。
如果不选择cpu的话，正常

下面是后台报错：
2017-07-12 19:06:47 +08:00: [Easy-Monitor: dashboard <24953>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
12|cluster | 2017-07-12 19:06:47 +08:00: [Easy-Monitor: embrace <24942>] common.socket->onData error: TypeError: Cannot read property 'profilerP' of undefined
12|cluster | 2017-07-12 19:06:47 +08:00: [Easy-Monitor: dashboard <24953>] common.socket->onData error: TypeError: Cannot read property 'composeKey' of undefined
12|cluster | 2017-07-12 19:06:47 +08:00: [Easy-Monitor: dashboard <24953>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
12|cluster | 2017-07-12 19:06:47 +08:00: [Easy-Monitor: dashboard <24953>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
12|cluster | 2017-07-12 19:06:47 +08:00: [Easy-Monitor: dashboard <24953>] http.axios.detail error: TypeError: Cannot read property 'composeKey' of undefined
12|cluster | 2017-07-12 19:07:04 +08:00: [Easy-Monitor: dashboard <24953>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
12|cluster | 2017-07-12 19:07:04 +08:00: [Easy-Monitor: dashboard <24953>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
12|cluster | [Easy-Monitor: dashboard <24953>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
12|cluster | 2017-07-12 19:07:04 +08:00: [Easy-Monitor: dashboard <24953>] http.axios.detail error: TypeError: Cannot read property 'composeKey' of undefined

如果有时间的话，能否定位一下问题出在哪？
多谢。

**Comment by hyj1991** [comment]
你好，话说出问题的 Easy-Monitor 版本，你使用的 node 和 npm 版本以及 window | linux | mac 平台信息方便留一下嘛

看错误栈信息，似乎是缺少文件，按理来说这些文件都是下载包的时候都在的，除非你安装的时候就缺失了这些文件。

或者你可以重新安装下看看还有这个错误没

**Comment by Ali1213** [comment]
多谢你提供的说是缺少文件，找到解决办法了。
我的node版本是6.10.1

然后我执行了 npm install -g node-pre-gyp
就把问题解决了。

似乎有些工具的安装依赖于全局的node-pre-gyp

多谢！

**Comment by hyj1991** [comment]
@Ali1213 不客气哇

包里用到了 v8-profiler，这个模块可能会需要编译~
