### ISSUE TITLE
web页面可以增加虚拟目录吗? 

### ISSUE THREAD

**Issue by dbit-xia** [hyj1991/easy-monitor#20]
由于正式服务器开放的端口有限, easymonitor 的 web页面可以增加虚拟目录吗? 以便实现path转发

**Comment by hyj1991** [comment]
@dbit-xia 能详细描述一下么，没有理解哇

**Comment by dbit-xia** [comment]
@hyj1991 就是所有的web请求 都加一个前缀,我试着设置了下面这个,[host]/monitor/index 页面却加载不出来
![image](https://user-images.githubusercontent.com/19259623/28203375-1472d4ce-68ac-11e7-8f76-42dceb42e837.png)

**Comment by hyj1991** [comment]
@dbit-xia 明白了，其实如你所见，我之前是想过加这个功能的，因此代码中配置保留了痕迹
但是后来因为静态资源部分用 vue 写的，vue 的客户端路由规则是打包的时候写进去的，所以一直没想好怎么做。

这个功能我再看一下，争取下个版本加入进去~

**Comment by dbit-xia** [comment]
谢谢, 恕我比较菜,vue打包不熟 也试着改了但结果都是失败的 ⊙﹏⊙‖∣

**Comment by hyj1991** [comment]
@dbit-xia 快改完了，我大致有好的思路了，估计今晚能发新版本

**Comment by hyj1991** [comment]
@dbit-xia 已完成，见 [commit#a76340fcb379800636da1ed87427784536de371e](https://github.com/hyj1991/easy-monitor/commit/a76340fcb379800636da1ed87427784536de371e)

等测试后发布新版本 v2.1.4 合并

**Comment by hyj1991** [comment]
@dbit-xia 

已发布新版本 v2.1.4，合并支持虚拟路径转发功能，使用方法和 nginx 配置参考见: [虚拟路径转发](http://www.easy-monitor.cn/document/#/?id=-%e8%99%9a%e6%8b%9f%e8%b7%af%e5%be%84%e8%bd%ac%e5%8f%91)

**Comment by dbit-xia** [comment]
给力 ,刚测试没问题,我先放上去再观察一下

**Comment by hyj1991** [comment]
@dbit-xia 好的，感谢提出宝贵建议~

**Comment by dbit-xia** [comment]
http://localhost:12333/dist/2.chunk.js

**Comment by dbit-xia** [comment]
亲,转发后有问题了, 这两个文件没有前缀,页面加载不出来
http://localhost:12333/dist/24712f6c47821394fba7942fbb52c3b2.ttf
http://localhost:12333/dist/2.chunk.js

**Comment by dbit-xia** [comment]
亲,转发后有问题了, 这两个文件没有前缀,页面加载不出来
http://localhost:12333/dist/24712f6c47821394fba7942fbb52c3b2.ttf
http://localhost:12333/dist/1.chunk.js
http://localhost:12333/dist/2.chunk.js

**Comment by dbit-xia** [comment]
亲,转发后有问题了, 这两个文件没有前缀,页面加载不出来
http://localhost:12333/dist/24712f6c47821394fba7942fbb52c3b2.ttf
http://localhost:12333/dist/2.chunk.js
http://localhost:12333/dist/0.chunk.js
http://localhost:12333/dist/1.chunk.js

**Comment by hyj1991** [comment]
@dbit-xia 我看了下确实，你提到的几个文件里面的 publicPath 都是打包的时候自动打进去的，我再想个办法做动态替换。

**Comment by dbit-xia** [comment]
亲,再问一下经过easy-monitor看到我的rss很高,有什么好的分析办法么?

**Comment by hyj1991** [comment]
@dbit-xia rss 属于堆外的，不会影响到 Node 进程内存溢出，如果你的连接很多的话也是正常的，这部分暂时不太好分析

**Comment by hyj1991** [comment]
@dbit-xia 已经修正了你提到的这个 BUG，有问题的 v2.1.4 版本取消了，你可以试下最新发布的 v2.1.5 观察下转发还有别的问题没~

**Comment by dbit-xia** [comment]
![image](https://user-images.githubusercontent.com/19259623/28243470-b8d17dc0-69fd-11e7-8d1e-4aeda8dda9ac.png)
目前还没有发现问题

**Comment by hyj1991** [comment]
@dbit-xia 👌

**Comment by MrSeaWave** [comment]
> @dbit-xia
> 
> 已发布新版本 v2.1.4，合并支持虚拟路径转发功能，使用方法和 nginx 配置参考见: [虚拟路径转发](http://www.easy-monitor.cn/document/#/?id=-%e8%99%9a%e6%8b%9f%e8%b7%af%e5%be%84%e8%bd%ac%e5%8f%91)

@hyj1991 请问3.0的版本该如何配置虚拟路径转发呢？

**Comment by hyj1991** [comment]
> @hyj1991 请问3.0的版本该如何配置虚拟路径转发呢？

不支持，你把 3.0 的监控服务端理解成一个独立的应用服务，不应该绑定到某个路径下
