### ISSUE TITLE
index页面选择MEM，再start没有到预期统计页面

### ISSUE THREAD

**Issue by Bingchean** [hyj1991/easy-monitor#22]
部署在阿里云上
http://114.55.8.96:12333/index

**Comment by hyj1991** [comment]
@BingChean

我看了下，服务器返回了错误：
```bash
{"success":false,"code":3,"error":"服务器内部错误!"}
```

因为不想暴露服务器的内部数据，所以没有返回错误的栈信息，如果你能 ssh 到你的服务器的话，可以看下错误日志，我这边是有错误信息输出的~

**Comment by Bingchean** [comment]
我可以ssh上去的，我看到报错：
[Easy-Monitor: dashboard <1164>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined

{"success":false,"code":3,"error":"服务器内部错误!"} 这个错是哪里返回的，我的阿里云server么，还是您那边。

**Comment by hyj1991** [comment]
@Bingchean 你的阿里云，我这个项目是完全开源的，C/S 全部在你自己这边控制的

**Comment by hyj1991** [comment]
@Bingchean 你可以 ssh 上去的话，看你贴出来的错误，像是文件缺失导致的，要不你先检查下：

* node_modules/easy-monitor/src_logic/common/common.socket.js 
* node_modules/easy-monitor/src_logic/config/config.profiler.js 

这两个文件在不在。

如果这两个文件存在，那你 ssh 上去手动把项目的 **node_modules/easy-monitor/src_logic/dashboard/controller/http/http.axios.profiler.js** 中的第 131 行从：

```js
dbl.error(`http.axios.profiler error: ${e}`);
```

改为:

```js
dbl.error(`http.axios.profiler error: ${e.stack}`);
```

然后再看下执行 cpu / mem 操作的时服务器的报错具体栈信息。

**Comment by Bingchean** [comment]
${e.stack} 打出栈内容：
node_modules/easy-monitor/src_logic/dashboard/controller/http/http.axios.profiler.js:28:36)

具体我看是：
initCache 函数的
        //组装缓存 key
        const key = common.profiler.composeKey(params); // 这一行，像是没找到composeKey？

然后
easy-monitor/src_logic/common/common.socket.js
easy-monitor/src_logic/config/config.profiler.js
这两个类都是存在的

具体全部栈内容：
```
[Easy-Monitor: dashboard <28990>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
    at initCache (/home/axinfu/axinfu_v3_h5/node_modules/easy-monitor/src_logic/dashboard/controller/http/http.axios.profiler.js:28:36)
    at initCache.next (<anonymous>)
    at onFulfilled (/home/axinfu/axinfu_v3_h5/node_modules/co/index.js:65:19)
    at /home/axinfu/axinfu_v3_h5/node_modules/co/index.js:54:5
    at co (/home/axinfu/axinfu_v3_h5/node_modules/co/index.js:50:10)
    at toPromise (/home/axinfu/axinfu_v3_h5/node_modules/co/index.js:118:63)
    at next (/home/axinfu/axinfu_v3_h5/node_modules/co/index.js:99:29)
    at onFulfilled (/home/axinfu/axinfu_v3_h5/node_modules/co/index.js:69:7)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by hyj1991** [comment]
@Bingchean 这就很奇怪了，你看下

node_modules/easy-monitor/src_logic/common/common.profiler.js

这个文件里最后 return 的内容，v2.1.5 的应该是这样：

```js
return { template, composeKey, profilerP, analyticsP }
```

还有就是你看下你的进程启动的时候， Easy-Monitor 初始化有报错信息么

**Comment by Bingchean** [comment]
`return { template, composeKey, profilerP, analyticsP }`

是这样的

**Comment by Bingchean** [comment]
哦看到启动报错了
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v5.7.6/node-v51-linux-x64/profiler.node'

**Comment by hyj1991** [comment]
@Bingchean 那基本上就是 Easy-Monitor 启动的时候初始化 common 文件夹下的东西因为某些原因失败了，你 ssh 进阿里云的控制台，打开一下项目日志，然后重启，看看有什么错误提示信息么？

**Comment by hyj1991** [comment]
@Bingchean 那错误愿意找到了，安装的时候安装 v8-profiler-node8 这个包应该是失败了，你可以先手动安装下这个包看看：

```bash
npm install v8-profiler-node8
```

这个包在 Node v7.5.0 下需要重新编译，我估计是你的阿里云服务器环境没有 node-gyp 导致的安装失败，如果是这个问题，先执行下：

```bash
sudo npm install node-gyp -g
```
再安装下这个包应该就好了

**Comment by hyj1991** [comment]
@Bingchean 不过我个人建议，线上部署 LTS 版本，目前 node8 尚未稳定，可以在线上部署 v6.x 的稳定版本~

**Comment by Bingchean** [comment]
好的，感谢，我先试试

**Comment by hyj1991** [comment]
@Bingchean 👌

**Comment by Bingchean** [comment]
`root@iZ23fywttoeZ:/home# npm install node-gyp -g
/usr/bin/node-gyp -> /usr/lib/node_modules/node-gyp/bin/node-gyp.js
/usr/lib
└── node-gyp@3.6.2 
`
阿里云上安装 node-gyp应该是成功的。


然后nodejs项目内安装 v8-profiler-node8
`axinfu-v3-h5@0.0.0 E:\work_axf\Server\source_code\axinfu_v3_h5
`-- easy-monitor@2.1.5
  `-- v8-profiler-node8@5.7.6`
应该也是对的，我是在本地Windows上项目目录文件夹下npm安装的，然后fabric发布到阿里云

这两个安装应该都是正确的。
我看错误还是存在的。

**Comment by hyj1991** [comment]
@Bingchean 你不能把你 windows 下的 v8-profiler-node8 直接发到阿里云哇。。。
因为你的是 windows，阿里云上是 linux，系统不一样，二进制文件是不通用的。

你必须在阿里云服务器上安装，比较好的发布流程是 node_modules 不进版本库，只有 package.json 进版本库，然后在构建项目时执行

```bash
npm install
```

安装依赖包

**Comment by chping2125** [comment]
看你文档(http://easy-monitor.cn/document/#/?id=-%e5%85%bc%e5%ae%b9%e6%80%a7)上说，v8-profiler-node8 不是为了修复node v8.x 下使用 v8-profiler 的错误发布的吗？问我本地nodev6.10.1也是这个错误，并且安装v8-profiler-node8后成功了，这是为什么？

**Comment by hyj1991** [comment]
@chping2125 v6.10.1 应该是没问题的，你可以手动执行下

```bash
npm install v8-profiler-node8
```

看看是否可以安装成功呢？如果安装成功，就不会提示这个错误

**Comment by chping2125** [comment]
我是mac os，执行``npm install v8-profiler-node8``后，问题确实解决了。

**Comment by hyj1991** [comment]
@chping2125 这个错误肯定就是 npm install 的时候因为某种原因异常了，现在看起来，纯 js 的包很少会出现安装错误，但是涉及到扩展的包似乎很容易安装错误
