### ISSUE TITLE
您好，新手安装出错了

### ISSUE THREAD

**Issue by Qiubaowei** [hyj1991/easy-monitor#24]
npm i easy-monitor -g

> v8-profiler-node8@5.7.6 preinstall C:\Users\xaj\AppData\Roaming\npm\node_modules\easy-monitor\node     _modules\v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@5.7.6 install C:\Users\xaj\AppData\Roaming\npm\node_modules\easy-monitor\node_mo     dules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/no     de-v57-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.6 and node@8.1.0 (node-v57      ABI) (falling back to source compile with node-gyp)
▒ڴ˽▒▒▒▒▒▒▒▒һ▒▒▒▒▒▒һ▒▒▒▒Ŀ▒▒▒▒Ҫ▒▒▒ò▒▒▒▒▒▒ɣ▒▒▒▒▒ӡ▒/m▒▒▒▒▒ء▒
MSBUILD : error MSB4132: ▒޷▒ʶ▒𹤾߰汾▒▒2.0▒▒▒▒▒▒▒õĹ▒▒߰汾Ϊ "4.0"▒▒
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit c     ode: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xaj\AppData\Roaming\npm\node_modules\node-gyp\li     b\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\xaj\\AppData\\Roaming\\npm\     \node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\xaj\\A     ppData\\Roaming\\npm\\node_modules\\easy-monitor\\node_modules\\v8-profiler-node8\\build\\profiler\\     v5.7.6\\node-v57-win32-ia32\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\xaj\\     AppData\\Roaming\\npm\\node_modules\\easy-monitor\\node_modules\\v8-profiler-node8\\build\\profiler\     \v5.7.6\\node-v57-win32-ia32"
gyp ERR! cwd C:\Users\xaj\AppData\Roaming\npm\node_modules\easy-monitor\node_modules\v8-profiler-nod     e8
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\xa     j\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Us     ers\xaj\AppData\Roaming\npm\node_modules\easy-monitor\node_modules\v8-profiler-node8\build\profiler\     v5.7.6\node-v57-win32-ia32\profiler.node --module_name=profiler --module_path=C:\Users\xaj\AppData\R     oaming\npm\node_modules\easy-monitor\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v57-w     in32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\xaj\AppData\Roaming\npm\node_modul     es\easy-monitor\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:887:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\xaj\\AppData\\Roam     ing\\npm\\node_modules\\easy-monitor\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fa     llback-to-build"
node-pre-gyp ERR! cwd C:\Users\xaj\AppData\Roaming\npm\node_modules\easy-monitor\node_modules\v8-pro     filer-node8
node-pre-gyp ERR! node -v v8.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\xaj\AppData\Roaming\npm\node_modu     les\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\xaj\AppData\Roaming\npm\nod     e_modules\easy-monitor\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v57-win32-ia32\prof     iler.node --module_name=profiler --module_path=C:\Users\xaj\AppData\Roaming\npm\node_modules\easy-mo     nitor\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v57-win32-ia32' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xaj\AppData\Roaming\npm-cache\_logs\2017-07-27T08_25_24_414Z-debug.log

**Comment by hyj1991** [comment]
@Qiubaowei 你好，这个是因为你的 node 版本是 8.1.0，在这个最新版本下 Easy-Monitor 的依赖 v8-profiler-node8 里面的 c 模块需要重新生成 windows 下的编译包，但是编译的过程中出错了。

你可以看下本地环境的  C++ 构建工具有没有正确安装，可以参考下这里：[Windows 安装 Node 扩展准备工具](https://github.com/nodejs/node-gyp#on-windows)

当然更简单的解决方式是，使用 Node v6.x 及以下的版本，因为在这个版本下有官方编译好的二进制包直接下载，所以省掉了你本地编译的过程~

**Comment by Qiubaowei** [comment]
@hyj1991 谢谢您的回答，我还想知道一下如果我使用 Node v6.x 及以下的版本安装，再把node的版本升级到8.1，是不是就可以完美使用了呢？

**Comment by hyj1991** [comment]
@Qiubaowei 不可以的，v6 和 v8 编译得到的包不一样

**Comment by Qiubaowei** [comment]
@hyj1991 好的，谢谢您了。看来我还需要把本地的C++构建工具检查一下了

**Comment by hyj1991** [comment]
@Qiubaowei 好的，那我把问题关了~
