### ISSUE TITLE
怎么安装都说v8-profiler地址找不到,然后编译报错...该怎么解决呢

### ISSUE THREAD

**Issue by TOBOM** [hyj1991/easy-monitor#27]
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './bui
ld/profiler/v5.7.6/node-v57-win32-x64/profiler.node'

**Comment by hyj1991** [comment]
@TOBOM 执行下 ```npm install v8-profiler-node8``` 看看能不能安装成功
另外，因为 v8-profiler-node8 这个包属于扩展需要编译，所以不能跨平台，比如：你把在 windows 下安装好的包直接拷贝到 linux 服务器上，是无法执行的
