### ISSUE TITLE
请问浅引用和保留引用分别指的是什么

### ISSUE THREAD

**Issue by heqs** [hyj1991/easy-monitor#30]
请问浅引用和保留引用分别指的是什么

**Comment by hyj1991** [comment]
@heqs 浅引用就是 Heapdump 中的 shallow size 值，保留引用则是 retained size 值。
简单的说，shallow size 就是对象自身占据的大小，那么 retained size 就是这个对象引用的别的一些对象，并且这些被引用的对象是无法从 roots 节点到达的，那么很显然，这时候砍掉你查看的 retained size 的这个对象，这些对象因为从 root 节点不可达，所以会在下次 gc 的时候被一起回收，它们占据的空间也会随之回收。那么这些对象加起来的大小再加上对象自身的 shallow size，就是这个对象的 retained size 的值
