### ISSUE TITLE
axiosProfilerDetail 服务器内部错误

### ISSUE THREAD

**Issue by DerekYeung** [hyj1991/easy-monitor#31]
axiosProfilerDetail返回数据：{"success":false,"code":3,"error":"服务器内部错误!"}
无法进到分析页面

**Comment by DerekYeung** [comment]
看了一下代码发现是缺少v8-profiler-node8导致的
这里其实有一个问题是：如果开发环境是win 线上是linux 会产生需要重新编译的问题 但重新编译又会产生svn冲突问题..

**Comment by hyj1991** [comment]
@DerekYeung 为啥这会有 svn 冲突，你们把 node_modules 进了版本库么？

**Comment by hyj1991** [comment]
@DerekYeung 可以只把 package.json 进版本库，上线构建的时候执行 npm install --production 就行了，node_modules 文件很多很多，不太建议放进版本库

**Comment by DerekYeung** [comment]
@hyj1991 是的 我们两种方案都尝试过 后来也是因为环境问题经常有npm install失败导致down下来无法运行的 加上还有私库 现在就是一台机器专门install，其他机器只down...

**Comment by hyj1991** [comment]
@DerekYeung 直接搭建 cnpm 私有仓库吧，这样就不会有网络问题了
