### ISSUE TITLE
出现如下错误

### ISSUE THREAD

**Issue by 470054086** [hyj1991/easy-monitor#32]
node版本:v8.4.0
选择 CPU和mem监控的时候 出现如下错误
[Easy-Monitor: dashboard <10448>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <10448>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <10448>] http.axios.detail error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <10448>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined

**Comment by hyj1991** [comment]
@470054086 看看是不是部署的时候 v8-profiler-node8 这个包没有安装成功，这个如果你的 node 版本在 v6 以上，会需要本地编译，估计是 node-gyp 编译不通过

**Comment by hyj1991** [comment]
@470054086 抱歉，最近公司在做一个脱产培训，没时间弄 git，所以这么晚回复。这个问题具体的你可以手动在本地尝试下 **npm install v8-profiler-node8** 看看是否能够安装成功

具体可以参看 [issue#24 您好，新手安装出错了](https://github.com/hyj1991/easy-monitor/issues/24)

**Comment by 470054086** [comment]
谢谢你的回复,确实是v8-profiler-node8这个包没有装上的原因

**Comment by 470054086** [comment]
@hyj1991 已经搞定了 谢谢大牛

**Comment by xuke007** [comment]
@470054086  请问你是win系统吗？ 我这边为啥v8-profiler-node8 这个包始终安装不上
