### ISSUE TITLE
浏览器页面宽度小于1000时，index页面样式乱了

### ISSUE THREAD

**Issue by Kinghts** [hyj1991/easy-monitor#35]
![default](https://user-images.githubusercontent.com/7201507/31108206-538af458-a82a-11e7-881f-30c30eb311b3.PNG)

**Comment by hyj1991** [comment]
@neverthanmore 样式问题要靠你有空看下了~

**Comment by neverthanmore** [comment]
@hyj1991 我看下

**Comment by neverthanmore** [comment]
@Kinghts 下个版本合并此修复

**Comment by hyj1991** [comment]
@Kinghts 此 bug 已在 v2.1.9 版本修复
