### ISSUE TITLE
使用yarn安装的时候, 疑似abbrev出现问题, npm没有问题

### ISSUE THREAD

**Issue by muyu66** [hyj1991/easy-monitor#44]
问题可能是你所引用的abbrev出现问题。
npm install 可以正常安装
yarn add 是失败的，错误信息如下：

error An unexpected error occurred: "EINVAL: invalid argument, lstat '/mnt/c/Web/hrm_api/node_modules/abbrev/package.json'".

需要更详细的情况，请联系我

**Comment by neverthanmore** [comment]
npm 5+ 引入了 lock 机制，yarn 没有特别的优势，建议采用 npm 安装

**Comment by muyu66** [comment]
@neverthanmore  我看了一下，确认不是yarn的问题，也不是easy-monitor的问题，问题来自于 windows10 WSL最近的一次补丁( 关于文件格式 的)

**Comment by neverthanmore** [comment]
@muyu66 问题已经解决了？

**Comment by hyj1991** [comment]
@muyu66 赞
