### ISSUE TITLE
在node8.7.0下，安装v8-profiler可以成功，而v8-profiler-node8则失败

### ISSUE THREAD

**Issue by maidol** [hyj1991/easy-monitor#45]
已经按照 https://github.com/nodejs/node-gyp#on-windows 安装node-gyp ， python也设置好了。在node8.7.0下，安装v8-profiler可以成功，而v8-profiler-node8则失败

错误信息：

$ npm install -g v8-profiler-node8

> v8-profiler-node8@5.7.6 preinstall C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@5.7.6 install C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.6 and node@8.7.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  profiler.cc
  cpu_profiler.cc
  cpu_profile.cc
  cpu_profile_node.cc
c:\users\maifuquan\appdata\roaming\npm\node_modules\v8-profiler-node8\node_modules\nan\nan_new.h(208)
: warning C4244: 'argument': conversion from 'int64_t' to 'double', possible loss of data (compiling
source file ..\src\cpu_profile.cc) [C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-n
ode8\build\profiler.vcxproj]
  ..\src\cpu_profile.cc(82): note: see reference to function template instantiation 'v8::Local<v8::Nu
  mber> Nan::New<v8::Number,int64_t>(A0)' being compiled
          with
          [
              A0=int64_t
          ]
  heap_profiler.cc
  heap_snapshot.cc
..\src\heap_profiler.cc : warning C4819: The file contains a character that cannot be represented in
the current code page (936). Save the file in Unicode format to prevent data loss [C:\Users\maifuquan
\AppData\Roaming\npm\node_modules\v8-profiler-node8\build\profiler.vcxproj]
  heap_output_stream.cc
  heap_graph_node.cc
..\src\heap_snapshot.cc(101): warning C4244: 'argument': conversion from 'int64_t' to 'uint32_t', pos
sible loss of data [C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8\build\profi
ler.vcxproj]
..\src\heap_profiler.cc(77): fatal error C1018: unexpected #elif [C:\Users\maifuquan\AppData\Roaming\
npm\node_modules\v8-profiler-node8\build\profiler.vcxproj]
  heap_graph_edge.cc
..\src\heap_graph_node.cc(69): warning C4996: 'v8::Object::Has': was declared deprecated [C:\Users\ma
ifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8\build\profiler.vcxproj]
  c:\users\maifuquan\.node-gyp\8.7.0\include\node\v8.h(3156): note: see declaration of 'v8::Object::H
  as'
c:\users\maifuquan\appdata\roaming\npm\node_modules\v8-profiler-node8\node_modules\nan\nan_new.h(208)
: warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of data (compil
ing source file ..\src\heap_graph_node.cc) [C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-pr
ofiler-node8\build\profiler.vcxproj]
  ..\src\heap_graph_node.cc(126): note: see reference to function template instantiation 'v8::Local<v
  8::Number> Nan::New<v8::Number,std::size_t>(std::A0)' being compiled
          with
          [
              A0=std::size_t
          ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\maifuquan\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\maifuquan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\maifuquan\\AppData\\Roaming\\npm\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.6\\node-v57-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\maifuquan\\AppData\\Roaming\\npm\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.6\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\maifuquan\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\maifuquan\\AppData\\Roaming\\npm\\node_modules\\v8-profiler-node8\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8
node-pre-gyp ERR! node -v v8.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\maifuquan\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\maifuquan\AppData\Roaming\npm\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v57-win32-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\maifuquan\AppData\Roaming\npm-cache\_logs\2017-12-04T14_48_32_656Z-debug.log

**Comment by hyj1991** [comment]
@maidol 这么奇怪的错误，你看下 node_modules/v8-profiler-node8/src/heap_profiler.cc 这个文件的 76 和 77 行呢，应该是这样：

```c++
#if (NODE_MODULE_VERSION > 0x0038)
    const HeapSnapshot* snapshot = v8::Isolate::GetCurrent()->GetHeapProfiler()->TakeHeapSnapshot();
```

提示的错误 [Fatal Error C1018](https://msdn.microsoft.com/en-us/library/8ad3xw5c.aspx) 我看了下没这个问题，而且我在 mac 上试了下 v8.7.0 也是可以编译的。

要是实在不行，你把 node 升级到当前的 lts 版本 v8.9.1 再试试看

**Comment by maidol** [comment]
![monitor](https://user-images.githubusercontent.com/4978561/33597636-01fa638e-d9db-11e7-90f5-fb4c27c7f991.png)
8.9.1我也试过了，也不行。我检查发现在我本机使用npm安装失败，对应的node_modules/v8-profiler-node8会自动移除掉了。我看到fork出来的仓库的代码是如图那样的第77行

**Comment by hyj1991** [comment]
@maidol 还有这种操作。。。你的 npm 源是官方的么？
我从来没见到过这个问题。。。npm 居然还能自动删代码 - =

**Comment by maidol** [comment]
使用的是taobao源

**Comment by hyj1991** [comment]
@maidol 你用 https://registry.npmjs.org 试试看呢

**Comment by maidol** [comment]
刚刚试了。也是一样的错误
 .\src\heap_profiler.cc(77): fatal error C1018: unexpected #elif [E:\markmai\my\easy-monitor\node_modules\v8-profiler-node8\build\pr
ofiler.vcxproj]

**Comment by hyj1991** [comment]
@maidol 你要不把 npm 也升个级吧，或者索性用 cnpm 安装试试看呢，文件被更改确实不知道为啥。。。

**Comment by maidol** [comment]
v8-profiler-node8的代码是你的仓库里面的master分支吗

**Comment by hyj1991** [comment]
@maidol 是的

**Comment by hyj1991** [comment]
@maidol 上游不维护了，我正打算抽空维护重写个 v8-profiler-next，顺便加上 heapProfile 和对应的 serialize

**Comment by maidol** [comment]
76和77行不是刚刚你说的：
#if (NODE_MODULE_VERSION > 0x0038)
    const HeapSnapshot* snapshot = v8::Isolate::GetCurrent()->GetHeapProfiler()->TakeHeapSnapshot();

我的截图是你的代码76和77
    const HeapSnapshot* snapshot = v8::Isolate::GetCurrent()->GetHeapProfiler()->TakeHeapSnapshot();
 #elif (NODE_MODULE_VERSION > 0x002C)

**Comment by hyj1991** [comment]
我仓库的代码有 **#if** ，而且也可以本地编译，行数可能会变没什么

**Comment by maidol** [comment]
我换成cnpm安装 也是报了
..\src\heap_profiler.cc(77): fatal error C1018: unexpected #elif [E:\markmai\my\easy-monitor\node_modules\\_v8-profiler-node8@5.7.6@v
8-profiler-node8\build\profiler.vcxproj]

对应的文件的截图
![monitor1](https://user-images.githubusercontent.com/4978561/33599322-c4901920-d9e0-11e7-9ecf-a0c46fd566f9.png)

**Comment by hyj1991** [comment]
@maidol 内容没错，我怀疑是文件编码的问题导致的。。。你把截图这个文件的:

```bash
#if (NODE_MODULE_VERSION > 0x0038)
    const HeapSnapshot* snapshot = v8::Isolate::GetCurrent()->GetHeapProfiler()->TakeHeapSnapshot();
```

删掉，然后手打进去，再在 node_modules/v8-profiler-node8 这个文件夹下执行：

```bash
npm rebuild
```

看看能不能编译成功

**Comment by maidol** [comment]
发现这个文件编码是utf-8，其他文件是ansi。我没有删除那两行代码并重新输入，直接 npm rebuild, 截图的提示是表示成功了还是失败啊？
![monitor2](https://user-images.githubusercontent.com/4978561/33600797-51e1f8bc-d9e5-11e7-804c-56543935c539.png)

**Comment by hyj1991** [comment]
@maidol 截图不全，看不出来，你找台 Linux 的机器部署看吧，win 下真心各种问题

**Comment by maidol** [comment]
截图就是这么多了

**Comment by maidol** [comment]
linux平台我之前试过都是ok的，没问题。就是在win下遇到了这个问题了

**Comment by hyj1991** [comment]
@maidol 肯定是和文件编码有关系，我后面重写的时候注意下这个方面吧

**Comment by maidol** [comment]
好的，谢谢

**Comment by hyj1991** [comment]
@maidol 👌

**Comment by SheenOh** [comment]
这个问题有解决方案吗 @hyj1991 
公司环境没法用window外的 系统。

**Comment by hyj1991** [comment]
@SheenOh 我在写 v8-profiler-next，会解决这个问题

**Comment by SheenOh** [comment]
@hyj1991 大神有计划什么时候更新吗？

**Comment by hyj1991** [comment]
@SheenOh v8-profiler-next 准备增加 v8-profiler 没有的 sampling heap profile，现在它在 4.x 下没有对应的 api，我在想办法做兼容

接下来的更新可能会慢一些，因为财年快到了我在公司内部也有一些项目得加紧做，如果有文件编码的问题你可以自己改下提个 pr，我来 merg 下

**Comment by SheenOh** [comment]
@hyj1991 
确实是编码问题。 改回unicode， 再用visual studio 手动编译一下就可以用了。
我今晚回去 提个pr 给 v8-profiler-node8

**Comment by hyj1991** [comment]
@SheenOh 棒棒哒
