### ISSUE TITLE
2.2.0最新版本下火焰图展示顶部按钮无法点击？

### ISSUE THREAD

**Issue by xujiandong2** [hyj1991/easy-monitor#49]
下载了最新的2.2.0版本，发现CPU页面以前可以点击的火焰图顶部的几个文字按钮还在但是无法点击了

**Comment by neverthanmore** [comment]
@xujiandong2 作者周末陪女票浪了，下周发新版本修复哦！

**Comment by neverthanmore** [comment]
@xujiandong2 这周比较忙，下周修复！

**Comment by xujiandong2** [comment]
@neverthanmore  谢谢，还有顺便请问下大神什么是Retained Size？怎么根据提示的内存泄漏定位到代码里的具体位置？新手不太会用

**Comment by neverthanmore** [comment]
@xujiandong2 retained size 就是一个 node 节点在支配树上下属直接支配节点的内存之和加上其自身的内存大小，通俗的讲就是把这个节点砍掉，v8 堆能回收的内存大小

**Comment by neverthanmore** [comment]
@xujiandong2 然后内存泄漏提示的图有一个泄漏关键字，去代码里面搜泄漏关键字给出来的那些 key，在代码里能搜到的地方看看逻辑有没有问题，更深入一点的可以去看 README 中提到的图文指南

**Comment by xujiandong2** [comment]
谢谢大神

**Comment by hyj1991** [comment]
@xujiandong2 done，2.2.1 版本发布，解决了这个 bug
