### ISSUE TITLE
无法分析mem？

### ISSUE THREAD

**Issue by citveeli** [hyj1991/easy-monitor#50]
os可以，选择cpu或者mem就返回这个
{"success":false,"code":3,"error":"服务器内部错误!"}
求解……

**Comment by hyj1991** [comment]
你看看启动应用的时候有没有报错信息，我估计是 v8-proflier-node8 这个模块安装错误

**Comment by citveeli** [comment]
没任何错误。

**Comment by hyj1991** [comment]
你把启动日志复制这边看看，还有点击 mem 操作的时候前端提示错误时服务端打印了的错误日志也贴过来看看呢

**Comment by citveeli** [comment]
找到问题了，没翻墙，v8-proflier-node8没下载到……

**Comment by hyj1991** [comment]
@citveeli 可以用 cnpm 国内镜像，不需要翻墙
