### ISSUE TITLE
Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz

### ISSUE THREAD

**Issue by liantiantian** [hyj1991/easy-monitor#51]
npm install easy-monitor的时候会报两个错，但是好像也不影响项目运行

ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.6 and node@8.1.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by hyj1991** [comment]
@liantiantian 这个其实是 warning
是这样的，v8-profiler-node8 是一个 c++ 扩展，install 的时候首先根据你的系统和 node 版本去 `node-inspector.s3.amazonaws.com``` 这里查看有没有编译好的 binary，如果有就直接下载拿来 require 了，没有则退化为本地编译：`node-gyp rebuild` 操作

这个错误就是第一次查找直接编译好的 binary 没有找到提示出来的，如果后面本地编译操作没有提示错误那就没有问题

**Comment by hyj1991** [comment]
先关闭问题了，有疑问可以继续在这里打开 issue 讨论
