### ISSUE TITLE
npm install easy-monitor安装报错，npm install v8-profiler-node8也是

### ISSUE THREAD

**Issue by fairyly** [hyj1991/easy-monitor#53]
我安装 npm install v8-profiler-node8
系统：win7  64 位  

gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=K:\NodeJS\nodetest\node_modules\v8-profiler-node8\build\profil
er\v5.7.6\node-v57-win32-ia32\profiler.node --module_name=profiler --module_path
=K:\NodeJS\nodetest\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v5
7-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (K:\NodeJS\nodetest\node
_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:209:5)

**Comment by hyj1991** [comment]
你看下环境变量里有 node-gyp 没？在 cmd 里直接执行下 node-gyp 看看

**Comment by fairyly** [comment]
C:\Users\fairy>node-gyp

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `msbuild` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates MSVC project files for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@3.6.2  C:\Users\fairy\AppData\Roaming\npm\node_modules\node-gyp
node@8.9.3

C:\Users\fairy>path
PATH=C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36
-32\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32
\WindowsPowerShell\v1.0\;I:\Program Files\TortoiseSVN\bin;i:\Program Files\Git\c
md;I:\Program Files\nodejs\;I:\Python27;i:\Python27\Scripts;C:\Windows\system32;
C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
I:\Program Files\TortoiseSVN\bin;C:\Users\fairy\AppData\Roaming\npm;I:\Python27;
i:\Python27\Scripts;

**Comment by fairyly** [comment]
环境变量里没有的呢

**Comment by hyj1991** [comment]
参考下这个 [issue#24](#24)

里面有 windows 安装的一些环境准备

**Comment by fairyly** [comment]
c++ ,vs .net都安装了，
node-pre-gyp ERR! node -v v8.9.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=K:\NodeJS\eas
y-monitor\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v57-win32-ia
32\profiler.node --module_name=profiler --module_path=K:\NodeJS\easy-monitor\nod
e_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v57-win32-ia32' (1)
npm WARN co-mocha@1.2.1 requires a peer of mocha@>=1.18 <5 but none is installed
. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.6 install: `node-pre-gyp install --fallback-to-bu
ild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fairy\AppData\Roaming\npm-cache\_logs\2018-01-28T07_37_20_

**Comment by hyj1991** [comment]
@fairyly  这两行给出了完整的错误信息，你打开这个文件贴出来看下

```bash
npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\fairy\AppData\Roaming\npm-cache_logs\2018-01-28T07_37_20_
```

**Comment by fairyly** [comment]
1625 silly install v8-profiler-node8@5.7.6
1626 info lifecycle v8-profiler-node8@5.7.6~install: v8-profiler-node8@5.7.6
1627 verbose lifecycle v8-profiler-node8@5.7.6~install: unsafe-perm in lifecycle true
1628 verbose lifecycle v8-profiler-node8@5.7.6~install: PATH: I:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;K:\NodeJS\nodetest\node_modules\v8-profiler-node8\node_modules\.bin;K:\NodeJS\nodetest\node_modules\.bin;C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;I:\Program Files\TortoiseSVN\bin;i:\Program Files\Git\cmd;I:\Program Files\nodejs\;I:\Python27;i:\Python27\Scripts;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\fairy\AppData\Roaming\npm
1629 verbose lifecycle v8-profiler-node8@5.7.6~install: CWD: K:\NodeJS\nodetest\node_modules\v8-profiler-node8
1630 silly lifecycle v8-profiler-node8@5.7.6~install: Args: [ '/d /s /c', 'node-pre-gyp install --fallback-to-build' ]
1631 silly lifecycle v8-profiler-node8@5.7.6~install: Returned: code: 1  signal: null
1632 info lifecycle v8-profiler-node8@5.7.6~install: Failed to exec install script
1633 verbose unlock done using C:\Users\fairy\AppData\Roaming\npm-cache\_locks\staging-185db09e7fd46375.lock for K:\NodeJS\nodetest\node_modules\.staging
1634 verbose stack Error: v8-profiler-node8@5.7.6 install: `node-pre-gyp install --fallback-to-build`
1634 verbose stack Exit status 1
1634 verbose stack     at EventEmitter.<anonymous> (I:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
1634 verbose stack     at emitTwo (events.js:126:13)
1634 verbose stack     at EventEmitter.emit (events.js:214:7)
1634 verbose stack     at ChildProcess.<anonymous> (I:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1634 verbose stack     at emitTwo (events.js:126:13)
1634 verbose stack     at ChildProcess.emit (events.js:214:7)
1634 verbose stack     at maybeClose (internal/child_process.js:925:16)
1634 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1635 verbose pkgid v8-profiler-node8@5.7.6
1636 verbose cwd K:\NodeJS\nodetest
1637 verbose Windows_NT 6.1.7601
1638 verbose argv "I:\\Program Files\\nodejs\\node.exe" "I:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "easy-monitor"
1639 verbose node v8.9.3
1640 verbose npm  v5.5.1
1641 error code ELIFECYCLE
1642 error errno 1
1643 error v8-profiler-node8@5.7.6 install: `node-pre-gyp install --fallback-to-build`
1643 error Exit status 1
1644 error Failed at the v8-profiler-node8@5.7.6 install script.
1644 error This is probably not a problem with npm. There is likely additional logging output above.
1645 verbose exit [ 1, true ]

**Comment by hyj1991** [comment]
@fairyly ELIFECYCLE 看起来像是 Windows 下用户权限导致的问题，你看看用 Admin 用户执行下呢

**Comment by fairyly** [comment]
@hyj1991 目前是在管理员权限执行的

**Comment by hyj1991** [comment]
@fairyly 你要不试下 npm install v8-profiler 或者 npm install v8-profiler-next 这个两个包看看能不能成功，win 下安装扩展是会出现各种奇怪的问题...

**Comment by fairyly** [comment]
@hyj1991 暂时都不行,目前还是 window 上有问题的,等两天再试试,谢谢了

**Comment by hyj1991** [comment]
@fairyly 好的
