### ISSUE TITLE
安装easy-monitor失败

### ISSUE THREAD

**Issue by yanghuo662** [hyj1991/easy-monitor#57]
错误提示：
C:\Users\defaultuser0>npm install easy-monitor

> v8-profiler-node8@5.7.6 preinstall C:\Users\defaultuser0\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@5.7.6 install C:\Users\defaultuser0\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.6 and node@9.5.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "D:\python\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\defaultuser0\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.6\\node-v59-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\defaultuser0\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.6\\node-v59-win32-x64"
gyp ERR! cwd C:\Users\defaultuser0\node_modules\v8-profiler-node8
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\defaultuser0\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v59-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\defaultuser0\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v59-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\defaultuser0\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\defaultuser0\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\defaultuser0\node_modules\v8-profiler-node8
node-pre-gyp ERR! node -v v9.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\defaultuser0\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v59-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\defaultuser0\node_modules\v8-profiler-node8\build\profiler\v5.7.6\node-v59-win32-x64' (1)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\defaultuser0\package.json'
npm WARN defaultuser0 No description
npm WARN defaultuser0 No repository field.
npm WARN defaultuser0 No README data
npm WARN defaultuser0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\defaultuser0\AppData\Roaming\npm-cache\_logs\2018-02-27T06_49_25_625Z-debug.log

**Comment by SheenOh** [comment]
@yanghuo662 你没有安装c++ 编译环境
https://github.com/nodejs/node-gyp#on-windows

**Comment by hyj1991** [comment]
缺少了 python

```bash
gyp ERR! stack Error: Can't find Python executable "D:\python\python.EXE", you can set the PYTHON env variable.
```

**Comment by hyj1991** [comment]
如还有问题，再打开 issue 讨论
