### ISSUE TITLE
关于输出的问题

### ISSUE THREAD

**Issue by SLRXXX** [hyj1991/easy-monitor#58]
请问一下，如果想把monitor的结果按每分或每秒输出到日志文件里，是否能通过现有的接口来完成这个需求，性能开销如何

**Comment by hyj1991** [comment]
不可能的，这么做性能巨差

**Comment by SLRXXX** [comment]
那如果只提取几个关键指标呢？

**Comment by hyj1991** [comment]
只要不频繁做 profiling，就没问题，不过不做 profiling，也就是常见的运维指标罢了，没必要在这个项目上进行开发

**Comment by SLRXXX** [comment]
好的明白了，谢谢

**Comment by hyj1991** [comment]
不客气
