### ISSUE TITLE
项目是使用node-webkit打包成的桌面应用，应该如何配置easy-monitor

### ISSUE THREAD

**Issue by yanghuo662** [hyj1991/easy-monitor#60]
项目是使用node-webkit框架打包的桌面应用，怎么配置easy-monitor呢？
配置文件package.json中main指定的入口文件是html，其中初始化代码是JS：
<script type="text/javascript">
			seajs.config({
				base: "./views/",
				alias: {
					"jquery": "../scripts/libs/jquery-1.9.1.js"
				},
				paths: {
				}
			});			
			
			//初始化app
			seajs.use("entry.js", function(entry){
				entry.initLogin();
			});

		</script>

**Comment by hyj1991** [comment]
@yanghuo662 没有考虑过这样的客户端场景呢，抱歉，期待你的实践，可以加我钉钉讨论下，钉钉号：hyj1991
