### ISSUE TITLE
希望支持用express中间件挂载

### ISSUE THREAD

**Issue by dovewi** [hyj1991/easy-monitor#63]
app部署在SAE和BAE这样的平台,端口只有一个,如果挂了easy-monitor,那就没法用express了

**Comment by hyj1991** [comment]
可以配置虚拟路径转发的，参考文档：[虚拟路径转发](http://easy-monitor.cn/document/#/?id=-%e8%99%9a%e6%8b%9f%e8%b7%af%e5%be%84%e8%bd%ac%e5%8f%91)

**Comment by hyj1991** [comment]
先关闭了，有问题继续讨论
