### ISSUE TITLE
请问一个性能问题。

### ISSUE THREAD

**Issue by whtiehack** [hyj1991/easy-monitor#65]
对于embrace进程，如果在dashboard上没有任何操作的话，会影响应用的性能吗？

大概是这个意思
```
const easyMonitor = require('easy-monitor');
easyMonitor({
    cluster: true,
    bootstrap: 'embrace',
    project_name: 'Game Boy',
    /**
     @param {string} tcp_host 填写你部署的 dashboard 进程所在的服务器 ip
     @param {number} tcp_port 填写你部署的 dashboard 进程所在的服务器 端口
     **/
    embrace: {
        tcp_host: '127.0.0.1',
        tcp_port: 30000
    }
});
```
在业务进程内开启这个模块。不分析的情况下，会不会影响性能？
我翻了一遍文档没有这方面的介绍。
感谢。

**Comment by hyj1991** [comment]
@whtiehack 不做任何操作的话，所有的开销只有一个 60s 心跳一次的 tcp 连接保活，对性能的影响是微乎其微的。
不过这个工具建议在线下调试使用或者当做学习的工具，线上定位故障或者调优性能最佳的选择目前还是 [Node.js 性能平台](https://node.console.aliyun.com)，毕竟已经免费了

**Comment by whtiehack** [comment]
@hyj1991  感谢解答。

**Comment by whtiehack** [comment]
ali那货感觉太麻烦了，公司开发机还是win。头疼
