### ISSUE TITLE
dashboard子页面不停的在晃

### ISSUE THREAD

**Issue by whtiehack** [hyj1991/easy-monitor#66]
dashboard的 web页面，打开以后就高频率的左右晃动。

chrome版本 65.0.3325.181（正式版本） （64 位）
开始以为是插件问题，用隐私模式，还是一样晃，
 打开http://easy-monitor.cn/index 这个也是一样的晃
。

打开开发者工具就出现奇迹了。不晃了。。。

**Comment by whtiehack** [comment]
主页不晃，晃的是点start以后的子页面。

**Comment by hyj1991** [comment]
@neverthanmore 帮忙看下这个问题呢，我这边换了几个浏览器都没啥问题，你看看控制台有没有报错信息

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/39391817-62459a02-4adc-11e8-8692-1ba8d419f832.png)
控制台没有报错信息，只有这个。
开发者工具一关闭就又晃了。

![image](https://user-images.githubusercontent.com/12741016/39391820-806e6360-4adc-11e8-84a4-571c6e8469ff.png)
就是这个页面。  截图不影响。。

**Comment by hyj1991** [comment]
@whtiehack 我先看看能不能复现

**Comment by neverthanmore** [comment]
@whtiehack 提供一下浏览器版本

**Comment by whtiehack** [comment]
更新到新版本 不晃了
版本 67.0.3396.87（正式版本） （64 位）

**Comment by hyj1991** [comment]
@whtiehack 好吧... 看来是浏览器解析的问题
