### ISSUE TITLE
nodejs 10.0 不能用哈

### ISSUE THREAD

**Issue by whtiehack** [hyj1991/easy-monitor#67]
可能是这个库造成的  `v8-profiler-node8` . 10.0无法编译出这个库。

**Comment by whtiehack** [comment]
期待，感谢.这个库用起来挺好的。

**Comment by hyj1991** [comment]
@whtiehack
解决下了 v8-profiler-node8 在 node v10.x 下的一些 api 变更，同时更新了下 easy-monitor 对应的依赖包版本，目前已经支持 v10.x 下正常本地编译了~

这个 issue 先关闭了，如安装还有问题可以再打开在这边提问。
