### ISSUE TITLE
依赖无法下载

### ISSUE THREAD

**Issue by xyc-cn** [hyj1991/easy-monitor#68]
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazo
aws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.7 and
ode@8.7.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp

**Comment by hyj1991** [comment]
本来就没有对应 8.7.0 的 binary 哇。。。所有会 fallback 到本地编译的
因为 v8-profiler 的上游已经不维护了，编译好的 binary 只更新到 v6.x

**Comment by whtiehack** [comment]
老版本不支持可以理解，，但是能不能搞搞支持node10哇。。。。

**Comment by hyj1991** [comment]
@whtiehack Node 10 目前上游都一堆 bug，等有空看下怎么更新 binary 吧

**Comment by hyj1991** [comment]
@whtiehack @xyc-cn 
解决下了 v8-profiler-node8 在 node v10.x 下的一些 api 变更，同时更新了下 easy-monitor 对应的依赖包版本，目前已经支持 v10.x 下正常本地编译了~

这个 issue 先关闭了，如安装还有问题可以再打开在这边提问。
