### ISSUE TITLE
node v8.9.3利用npm v5.5.1安装时无法安装，报错如下

### ISSUE THREAD

**Issue by MrGengLei** [hyj1991/easy-monitor#70]
> v8-profiler-node8@5.7.8 preinstall D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@5.7.8 install D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@8.9.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8>if not defined npm_config_node_gyp (node "D:\softs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8>if not defined npm_config_node_gyp (node "D:\softs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\nod
e-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x
64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\softs\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\softs\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\softs\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\softs\\nodejs\\node.exe" "D:\\softs\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\webStrom\\hpalmConfig\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.8\\node-v57-win32-x64\\profiler.node" "--module_name=profi
ler" "--module_path=D:\\webStrom\\hpalmConfig\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.8\\node-v57-win32-x64"
gyp ERR! cwd D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\pr
ofiler\v5.7.8\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\webStrom\hpalmConfig\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "D:\\softs\\nodejs\\node.exe" "D:\\webStrom\\hpalmConfig\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x6
4' (1)
npm WARN Error: EPERM: operation not permitted, rmdir 'D:\webStrom\hpalmConfig\node_modules\node-pre-gyp'
npm WARN  { Error: EPERM: operation not permitted, rmdir 'D:\webStrom\hpalmConfig\node_modules\node-pre-gyp'
npm WARN   stack: 'Error: EPERM: operation not permitted, rmdir \'D:\\webStrom\\hpalmConfig\\node_modules\\node-pre-gyp\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'rmdir',
npm WARN   path: 'D:\\webStrom\\hpalmConfig\\node_modules\\node-pre-gyp' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\geng\AppData\Roaming\npm-cache\_logs\2018-05-24T01_23_52_267Z-debug.log

D:\webStrom\hpalmConfig>npm install v8-profiler-node8 --save-dev

> v8-profiler-node8@5.7.8 preinstall D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@5.7.8 install D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@8.9.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8>if not defined npm_config_node_gyp (node "D:\softs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8>if not defined npm_config_node_gyp (node "D:\softs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\nod
e-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x
64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\softs\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\softs\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\softs\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\softs\\nodejs\\node.exe" "D:\\softs\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\webStrom\\hpalmConfig\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.8\\node-v57-win32-x64\\profiler.node" "--module_name=profi
ler" "--module_path=D:\\webStrom\\hpalmConfig\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.8\\node-v57-win32-x64"
gyp ERR! cwd D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\pr
ofiler\v5.7.8\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\webStrom\hpalmConfig\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "D:\\softs\\nodejs\\node.exe" "D:\\webStrom\\hpalmConfig\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x6
4' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\geng\AppData\Roaming\npm-cache\_logs\2018-05-24T01_28_06_938Z-debug.log

D:\webStrom\hpalmConfig>
D:\webStrom\hpalmConfig>
D:\webStrom\hpalmConfig>npm install --save-dev easy-monitor

> v8-profiler-node8@5.7.8 preinstall D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@5.7.8 install D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@8.9.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8>if not defined npm_config_node_gyp (node "D:\softs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8>if not defined npm_config_node_gyp (node "D:\softs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\nod
e-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x
64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\softs\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\softs\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\softs\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\softs\\nodejs\\node.exe" "D:\\softs\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\webStrom\\hpalmConfig\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.8\\node-v57-win32-x64\\profiler.node" "--module_name=profi
ler" "--module_path=D:\\webStrom\\hpalmConfig\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.8\\node-v57-win32-x64"
gyp ERR! cwd D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\pr
ofiler\v5.7.8\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\webStrom\hpalmConfig\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "D:\\softs\\nodejs\\node.exe" "D:\\webStrom\\hpalmConfig\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\webStrom\hpalmConfig\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x6
4' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\geng\AppData\Roaming\npm-cache\_logs\2018-05-24T01_29_39_258Z-debug.log

**Comment by hyj1991** [comment]
缺少了 python

**Comment by hyj1991** [comment]
windows 下编译扩展，需要一些基础环境准备，你可以看下之前的相关 issue 里有写过一个链接，最终解决办法就是拥抱 mac，基本上不会遇到任何问题

**Comment by hyj1991** [comment]
windows 下编译扩展，需要一些基础环境准备，你可以看下之前的相关 issue 里有写过一个链接，最终解决办法就是拥抱 mac，基本上不会遇到任何问题

**Comment by MrGengLei** [comment]
windows下安装python后，依然无法安装成功；
需要准备什么基础环境呢

**Comment by MrGengLei** [comment]
@hyj1991 
windows下安装python后，依然无法安装成功；
需要准备什么基础环境呢

**Comment by whtiehack** [comment]
我猜你需要一个科学上网的工具。

**Comment by hyj1991** [comment]
@MrGengLei 之前在休假，手机不方便回复，window 下安装 node 扩展环境准备可以参考下这里：

[Windows 安装 Node 扩展准备工具](https://github.com/nodejs/node-gyp#on-windows)

**Comment by MrGengLei** [comment]
@hyj1991 谢谢哦，已经安装上了

**Comment by hyj1991** [comment]
@MrGengLei 嗯嗯，那我先关闭这个 issue 了，有问题可以 reopen
