### ISSUE TITLE
node v8.9.3项目，rss堆外内存一直上涨是什么原因呢

### ISSUE THREAD

**Issue by MrGengLei** [hyj1991/easy-monitor#71]
大家好，node v8.9.3项目，rss堆外内存一直上涨是什么原因呢？

**Comment by hyj1991** [comment]
堆外内存泄露可能是一些引用的 c++ 扩展泄露，暂时没有比较好的办法排查哦。只能用排查 c++  泄露的那套办法，比如 valgrind 或者 tcmalloc 替换等方法

**Comment by MrGengLei** [comment]
@hyj1991 
大神，我监控内存时，native占比95%表示什么，求解释？

ps:现在还不明白Type图中，各个指标的含义呢

**Comment by hyj1991** [comment]
@MrGengLei 
native objects 实际上不属于 v8 heap，一般 chrome 浏览器里的 statistics 视图会把 native 部分的内存占比去掉不展示，因此实际上堆快照的 total size = v8 heap + native size

native object 消耗的内存不由 v8 的垃圾回收器管理，即 gc 无法回收掉 native objects，它们实际上是 JS Wrapper 过的 c++ object，也只能通过 JS Wrapper 才能被 js 代码引用感知到的部分

你这个情况肯定是哪个 c++ 的扩展模块没写好有泄漏，可以看下 package.json，是不是有需要本地编译的包，去对应的 github 仓库里看看有没有内存泄漏的讨论

**Comment by MrGengLei** [comment]
@hyj1991 好的，谢谢指点，万分感谢

**Comment by hyj1991** [comment]
@MrGengLei 嗯，如果还有问题可以再打开这个 issue
