### ISSUE TITLE
火焰图显示不出来

### ISSUE THREAD

**Issue by KingDracula** [hyj1991/easy-monitor#73]
[Easy-Monitor] child_process calculator-> analytics error: RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:675:23)
    at process.target.send (internal/child_process.js:586:19)
    at Promise (E:\Git\eService.KM2.Frontend\node_modules\easy-monitor\src_logic\embrace\calculator.js:9:17)
    at new Promise (<anonymous>)
    at sendMessage (E:\Git\eService.KM2.Frontend\node_modules\easy-monitor\src_logic\embrace\calculator.js:8:12)
    at common.profiler.analyticsP.apply.then.analysis (E:\Git\eService.KM2.Frontend\node_modules\easy-monitor\src_logic\embrace\calculator.js:42:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by hyj1991** [comment]
@KingDracula 有更多信息么？比如 easy-monitor 版本，node 版本这些的
看起来是抓取到的 cpu profile 文件内容是不对的，导致解析出错
可以打开本地 node_modules/easy-monitor/src_logic/embrace/controller/tcp.profiler.js 下的这个文件，在第 62 行下面加上

```js
console.log(profiler)
```
看看输出的 cpu profile 内容是啥

**Comment by KingDracula** [comment]
easy-monitor版本是最新的，node是v8.11.2

**Comment by KingDracula** [comment]
我用的是win10，跟系统有关系吗？

**Comment by hyj1991** [comment]
@KingDracula 和系统应该没有关系，我在 windows 上测过，不过手里暂时没有 windows 的机器，我先试下 mac 下 node-v8.11.2 是不是正常的

**Comment by hyj1991** [comment]
这里试了下看起来 8.11.2 这个版本没问题，你要不按照我上面那段代码下加个 console.log，看看你这里采集到的 cpu profile 是什么内容呢？

**Comment by KingDracula** [comment]
这是打印输出的值
CpuProfile {
  delete: [Function: delete],
  typeId: 'CPU',
  uid: '1',
  title: 'Profile 1',
  head:
   { functionName: '(root)',
     url: '',
     lineNumber: 0,
     callUID: 2651,
     bailoutReason: '',
     id: 1,
     scriptId: 0,
     hitCount: 1,
     children:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  startTime: 689019,
  endTime: 689320,
  samples:
   [ 13,
     26,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     27,
     ... 285739 more items ],
  timestamps:
   [ 689020022322,
     689020023680,
     689020024705,
     689020025724,
     689020026853,
     689020027882,
     689020028902,
     689020029928,
     689020031045,
     689020032065,
     689020033080,
     689020034094,
     689020035109,
     689020036124,
     689020037175,
     689020038205,
     689020039224,
     689020040237,
     689020041252,
     689020042265,
     689020043323,
     689020044351,
     689020045369,
     689020046456,
     689020047482,
     689020048492,
     689020049501,
     689020050508,
     689020051515,
     689020052554,
     689020053567,
     689020054576,
     689020055585,
     689020056594,
     689020057603,
     689020058611,
     689020059659,
     689020060677,
     689020061695,
     689020062712,
     689020063724,
     689020064734,
     689020065748,
     689020066878,
     689020067895,
     689020068914,
     689020069928,
     689020070942,
     689020071968,
     689020072985,
     689020074017,
     689020075034,
     689020076054,
     689020077130,
     689020078157,
     689020079180,
     689020080202,
     689020081281,
     689020082299,
     689020083318,
     689020084333,
     689020085343,
     689020086353,
     689020087361,
     689020088369,
     689020089378,
     689020090386,
     689020091393,
     689020092404,
     689020093465,
     689020094489,
     689020095503,
     689020096511,
     689020097520,
     689020098527,
     689020099535,
     689020100542,
     689020101549,
     689020102557,
     689020103564,
     689020104577,
     689020105629,
     689020106647,
     689020107663,
     689020108673,
     689020109731,
     689020110746,
     689020111769,
     689020112793,
     689020113811,
     689020114823,
     689020115838,
     689020116852,
     689020117869,
     689020118883,
     689020119897,
     689020120970,
     689020121985,
     689020122994,
     689020124004,
     ... 285739 more items ] }

**Comment by hyj1991** [comment]
@KingDracula 你加我下钉钉吧：hyj1991，把这个对象 JSON.stringify 后用文件发给我看下，大致看结构这个 cpuprofile 倒是没啥问题

**Comment by hyj1991** [comment]
会尽快修复这个问题，感谢反馈

**Comment by hyj1991** [comment]
已修复，见 [pr#74](#74)

**Comment by hyj1991** [comment]
并不是大 json 的问题，cpu profile 确实不会很大，这个没有判断错，这里的错误其实是在你的 cpu profile 文件下 json 对象 parent 循环引用导致的

**Comment by hyj1991** [comment]
先关掉了，还有使用问题可以继续打开这个 issue
