### ISSUE TITLE
[RFC] 关于 Easy-Monitor 内存分析的疑问（优化内存泄漏计算模型）

### ISSUE THREAD

**Issue by clancytom** [hyj1991/easy-monitor#75]
我当前进程
![image](https://user-images.githubusercontent.com/25688775/41893376-2065413c-794e-11e8-9710-0bc9bd3580fa.png)
agent 进程，内存占用250m左右
![image](https://user-images.githubusercontent.com/25688775/41893523-918ff514-794e-11e8-8400-7d1e4f360efc.png)
这里显示无内存泄露，我如何能够看到内存具体是哪些内容，我先看下内存具体占用情况，是不是还需要自己手动导出heapdump文件，然后分析

**Comment by clancytom** [comment]
![image](https://user-images.githubusercontent.com/25688775/41893563-c1a8f8fe-794e-11e8-8b47-5a9e8c409804.png)

**Comment by hyj1991** [comment]
我大概知道原因了，dominator tree 计算的时候只取了 retainedSize 最大的节点，你这个情况很可能是大量的小字符串占比高

**Comment by hyj1991** [comment]
所以最大的 retainedSize 占比还是没达到我设置的阈值，既然知道了是字符串，那就把 snapshot 放到 devtools 里面，看下 strings 下面是什么字符串

**Comment by hyj1991** [comment]
这个算法我有打算用 c++ 重写优化下, 可以看下这个项目 [devtoolx](https://github.com/hyj1991/devtoolx)

**Comment by clancytom** [comment]
easy-monitor  采集到的snapshot 会保存吗？ 还是我需要额外自己再收集一份snapshot文件

**Comment by hyj1991** [comment]
暂时不会保存，不过你可以在 [tcp.profiler.js](https://github.com/hyj1991/easy-monitor/blob/master/src_logic/embrace/controller/tcp.profiler.js#L62) 下面加一行类似：
```js
profiler.pipe(require('fs').createWriteStream(`${__dirname}/xxx.snapshot`))
```
的方式输出到文件里

**Comment by hyj1991** [comment]
之前一个很久远的 issue 里有计划加上这个保存功能的，后来因为种种原因没有开发合并，欢迎 pr 哦

**Comment by JoMartinezZhu** [comment]
> profiler.pipe(require('fs').createWriteStream(`${__dirname}/xxx.snapshot`))

加载具体哪个位置，合适迷惑！

**Comment by hyj1991** [comment]
进展参见 #103

**Comment by hyj1991** [comment]
关联 #106
