### ISSUE TITLE
easy-monitor安装报错，已提前安装好v8-profiler-node8，依然报错

### ISSUE THREAD

**Issue by SFHfeihong** [hyj1991/easy-monitor#76]
os: centos7
node_verson: v8.9.2
问题：已将https://github.com/hyj1991/v8-profiler-node8 安装到node的gloable 环境，执行npm install easy-monitor -g 依然报错，似乎没有读取全局中的v8-profiler-node8模块

安装完成v8-profiler-node8日志：
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/node-v8.9.2-linux-x64/lib/node_modules/v8-profiler-node8/.node-gyp/8.9.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/node-v8.9.2-linux-x64/lib/node_modules/v8-profiler-node8/.node-gyp"
+ v8-profiler-node8@6.0.0
added 68 packages from 35 contributors in 183.851s

报错日志：
> v8-profiler-node8@5.7.8 preinstall /usr/local/node-v8.9.2-linux-x64/lib/node_modules/easy-monitor/node_modules/v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@5.7.8 install /usr/local/node-v8.9.2-linux-x64/lib/node_modules/easy-monitor/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@8.9.2 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@8.9.2 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
gyp ERR! command "/usr/local/node-v8.9.2-linux-x64/bin/node" "/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/node-v8.9.2-linux-x64/lib/node_modules/easy-monitor/node_modules/v8-profiler-node8
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node-v8.9.2-linux-x64/bin/node /usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/easy-monitor/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
node-pre-gyp ERR! command "/usr/local/node-v8.9.2-linux-x64/bin/node" "/usr/local/node-v8.9.2-linux-x64/lib/node_modules/easy-monitor/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/node-v8.9.2-linux-x64/lib/node_modules/easy-monitor/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v8.9.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/node-v8.9.2-linux-x64/bin/node /usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
gyp ERR! clean error | install: info lifecycle v8-profiler-node8@5.7.8~install: Failed to exec install script
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
gyp ERR! command "/usr/local/node-v8.9.2-linux-x64/bin/node" "/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/node-v8.9.2-linux-x64/lib/node_modules/easy-monitor/node_modules/v8-profiler-node8
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler-node8@5.7.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-09T06_47_43_586Z-debug.log

**Comment by hyj1991** [comment]
@SFHfeihong -g 安装到全局的意思是可以用 cli，不是全局共享这个 node_modules 哦
你这个错误貌似是权限错误，你确定在 npm install 的目录下有创建目录的权限么

> gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'

**Comment by SFHfeihong** [comment]
是呢，我是以root身份安装的，应该不存在权限的问题吧

**Comment by hyj1991** [comment]
手动执行下 npm i v8-profiler-node8，看看是啥错误，不要带 -g，-g 不是这么用的

**Comment by SFHfeihong** [comment]
手动执行 npm i v8-profiler-node8，报错日志：
> v8-profiler-node8@5.7.8 preinstall /root/node_modules/easy-monitor/node_modules/v8-profiler-node8
> node -e 'process.exit(0)'


> v8-profiler-node8@6.0.0 preinstall /root/node_modules/v8-profiler-node8
> node -e 'process.exit(0)'


> v8-profiler-node8@5.7.8 install /root/node_modules/easy-monitor/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@8.9.2 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@8.9.2 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
gyp ERR! command "/usr/local/node-v8.9.2-linux-x64/bin/node" "/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /root/node_modules/easy-monitor/node_modules/v8-profiler-node8
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node-v8.9.2-linux-x64/bin/node /usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
node-pre-gyp ERR! command "/usr/local/node-v8.9.2-linux-x64/bin/node" "/root/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/node_modules/easy-monitor/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v8.9.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/node-v8.9.2-linux-x64/bin/node /usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
gyp ERR! UNCAUGHT EXCEPTION ll: info lifecycle v8-profiler-node8@5.7.8~install: Failed to exec install script
gyp ERR! stack Error: ENOENT: no such file or directory, uv_cwd
gyp ERR! stack     at process.cwd (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:11:19)
gyp ERR! stack     at setopts (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/glob/common.js:93:21)
gyp ERR! stack     at new Glob (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/glob/glob.js:135:3)
gyp ERR! stack     at Function.glob.hasMagic (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/glob/glob.js:101:11)
gyp ERR! stack     at rimraf (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/rimraf/rimraf.js:62:36)
gyp ERR! stack     at clean (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/clean.js:20:3)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as clean] (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:55:37)
gyp ERR! stack     at run (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:87:30)
gyp ERR! stack     at Object.<anonymous> (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:148:1)
gyp ERR! stack     at Module._compile (module.js:635:30)
gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
gyp ERR! command "/usr/local/node-v8.9.2-linux-x64/bin/node" "/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:11
    cwd = origCwd.call(process)
                  ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:11:19)
    at errorMessage (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:134:28)
    at issueMessage (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:140:3)
    at process.<anonymous> (/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:124:3)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler-node8@5.7.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-09T07_30_46_817Z-debug.log

之前安装是通过： npm install https://github.com/hyj1991/v8-profiler-node8 --unsafe-perm 
安装结果是成功的

**Comment by hyj1991** [comment]
删掉你本地的 package-lock.json，这个包已经更新到 6.0.0 了，你这里还是很久以前的 5.7.8

**Comment by SFHfeihong** [comment]
删除之后包的版本到6.0.0了，但是报错依然与上面一样。
> v8-profiler-node8@6.0.0 install /usr/local/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for v8-profiler-node8@6.0.0 and node@8.9.2 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/node_modules/v8-profiler-node8/build/profiler/v6.0.0/node-v57-linux-x64' 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
gyp ERR! command "/usr/local/node-v8.9.2-linux-x64/bin/node" "/usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/node_modules/v8-profiler-node8
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node-v8.9.2-linux-x64/bin/node /usr/local/node-v8.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
node-pre-gyp ERR! command "/usr/local/node-v8.9.2-linux-x64/bin/node" "/usr/local/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v8.9.2
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok

**Comment by hyj1991** [comment]
你这错误就是没有权限:

> node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/node_modules/v8-profiler-node8/build/profiler/v6.0.0/node-v57-linux-x64'

你是下手动用当前账号执行下 `mkdir '/usr/local/node_modules/v8-profiler-node8/build/profiler/v6.0.0/node-v57-linux-x64'` 能成功么

**Comment by hyj1991** [comment]
这个错误很明显是创建目录和文件的时候失败了。。。

**Comment by SFHfeihong** [comment]
基于前面报错，这个文件夹/usr/local/node_modules/v8-profiler-node8/build/profiler/v6.0.0/node-v57-linux-x64我提前创建了，但执行完npm i v8-profiler-node8这个命令之后，此文件夹就本删除了

**Comment by hyj1991** [comment]
你为什么要装在 /usr/local 下面？这种模块直接安装到项目目录下就行了，尽量把包撞到用户目录下

**Comment by SFHfeihong** [comment]
安装在/usr/local下是因为有项目的那台机器防火墙的原因无法安装包。刚刚把项目拷贝过来了之后，问题依然如上。这个文件夹/usr/local/IPTVADService/node_modules/v8-profiler-node8/build/profiler/v6.0.0/node-v57-linux-x64我提前创建了，但执行完npm i v8-profiler-node8这个命令之后，此文件夹就又被删除了

**Comment by hyj1991** [comment]
这是 npm 的机制，本来重新安装一个包前就要清除掉同名文件的

**Comment by SFHfeihong** [comment]
那这个权限问题有什么办法解决一下呢？？我是root用户。

**Comment by hyj1991** [comment]
在用户目录下安装下试试看，没遇到过这样的问题

**Comment by SFHfeihong** [comment]
Hi，我换成普通用户安装，上述问题没有了。安装应该是不能用root用户安装。非常感谢！！！！

**Comment by hyj1991** [comment]
ok

**Comment by hyj1991** [comment]
@SFHfeihong 先关闭了，有其它问题再提 issue 哦
