### ISSUE TITLE
npm安装easy-monitor报错

### ISSUE THREAD

**Issue by bralion** [hyj1991/easy-monitor#77]
npm安装时报错了

![image](https://user-images.githubusercontent.com/12732119/43459020-b7dbbe1c-94fe-11e8-9414-504c822516db.png)

node版本 8.3.0  npm 版本 5.3.0

**Comment by hyj1991** [comment]
你这是权限出问题了吧，windows 下权限很迷，实在不行重启下电脑再试试看？

**Comment by bralion** [comment]
截错图了，有权限写入的时候也会抱错，下载包404

![image](https://user-images.githubusercontent.com/12732119/43464600-05c0886c-94cb-11e8-987e-c75934a5a1e4.png)

**Comment by bralion** [comment]
好的，谢谢了。我应该下一个python配置一下环境变量就好了

**Comment by hyj1991** [comment]
不客气哦，有问题可以继续在这边说

**Comment by bralion** [comment]
已经搞定了，好用

**Comment by hyj1991** [comment]
OK，那这个 issue 我先关闭了，有其它使用问题可以再发对应的 issue

**Comment by bralion** [comment]
嗯呢
