### ISSUE TITLE
node 8.9.0版本安装报错.

### ISSUE THREAD

**Issue by 119992278** [hyj1991/easy-monitor#78]
![qq 20180803155841](https://user-images.githubusercontent.com/35093311/43631663-6bade026-9736-11e8-8522-558342641b3c.png)

请求解决

**Comment by hyj1991** [comment]
你本地没有 vs ，不能编译 c++ 项目...

**Comment by hyj1991** [comment]
window 下安装扩展可以参考这个：[Windows 安装 Node 扩展准备工具](https://github.com/nodejs/node-gyp#on-windows)

**Comment by 119992278** [comment]
安装了node-gyp,framek也是最新版本的,但还是安装不成功.
![qq 20180806100540](https://user-images.githubusercontent.com/35093311/43693429-5f2f879c-9960-11e8-8265-43d5614af47a.png)

**Comment by hyj1991** [comment]
这和 easy-monitor 没什么关系呀，报错的是 **koa2-vue-demo-master**，看看你的 package.json 呢

**Comment by hyj1991** [comment]
@119992278 先关闭这个 issue 了，有问题可以继续打开
