### ISSUE TITLE
npm install easy-monitor fail

### ISSUE THREAD

**Issue by DinoFeng** [hyj1991/easy-monitor#79]
node -v
v8.11.1
npm -v
6.2.0
npm install easy-monitor

> v8-profiler-node8@5.7.8 preinstall D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@5.7.8 install D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@8.11.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\v8-profiler-node8\build\profiler.vcxproj(20,3): error MSB4019: 未找到导入的项目“D:\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中的路
径正确，且磁盘上存在该文件。
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\fengd\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fengd\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Dino_Project\\GitHub\\Esquel\\lpd-fabric-development\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.8\\node-v57-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=D:\\Dino_Project\\GitHub\\Esquel\\lpd-fabric-development\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.8\\node-v57-win32-x64"
gyp ERR! cwd D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\v8-profiler-node8
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\fengd\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Dino_Project\\GitHub\\Esquel\\lpd-fabric-development\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\v8-profiler-node8
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\fengd\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=D:\Dino_Project\GitHub\Esquel\lpd-fabric-development\node_modules\v8-profiler-node8\build\profiler\v5.7.8\node-v57-win32-x64' (1)
npm WARN grahpql-api@2.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fengd\AppData\Roaming\npm-cache\_logs\2018-08-30T06_09_04_126Z-debug.log

**Comment by DinoFeng** [comment]
[2018-08-30T06_09_04_126Z-debug.log](https://github.com/hyj1991/easy-monitor/files/2334792/2018-08-30T06_09_04_126Z-debug.log)

**Comment by hyj1991** [comment]
window 下安装扩展可以参考这个：[Windows 安装 Node 扩展准备工具](https://github.com/nodejs/node-gyp#on-windows)

**Comment by hyj1991** [comment]
v8-profiler-node8 这个包是扩展，需要本地编译

**Comment by DinoFeng** [comment]
是不是先npm install -g node-gyp
再npm install easy-monitor ？

**Comment by hyj1991** [comment]
node-gyp 是最后需要的，之前你还得有 Visual Studio，Python 等，具体上我第一条回复里面的内容

**Comment by DinoFeng** [comment]
@hyj1991 Thank you.
1. npm install --global --production windows-build-tools
2. npm install -g node-gyp
3. npm install easy-monitor
3个步骤，问题解决。

**Comment by hyj1991** [comment]
ok，那这个 issue 我关闭了
