### ISSUE TITLE
2.0 新版本发布

### ISSUE THREAD

**Issue by hyj1991** [hyj1991/easy-monitor#8]
全新重构的 2.0 已经发布: [Demo](http://easy-monitor.cn/index) & [Document](http://easy-monitor.cn/document)

使用有问题可以 issue 反馈，快速响应

**Comment by ruanzhijun** [comment]
嵌入项目 压测，用来监控数据，项目20分钟内重启了两次，内内存最高使用去到500+，平时我的项目压测封顶250就会降下去

**Comment by ruanzhijun** [comment]
pm2重启后，原来的进程还残留在里面

**Comment by ruanzhijun** [comment]
common.init.memwatchNext - memory leak...
common.init.memwatchNext - { growth: 18489440,
       reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
common.init.memwatchNext - memory diff...

**Comment by ruanzhijun** [comment]
就这样晾着没请求也内存泄露了

**Comment by hyj1991** [comment]
@ruanzhijun 留个联系方式，这里讲比较麻烦

**Comment by ruanzhijun** [comment]
@hyj1991 压测一个业务最复杂的接口(其实就是数据库查询最多的，有4-5个，我平时压测压到服务器网络堵塞了都不会泄漏的)，加个微信我把heapsnapshot发你看看，排在前面的都是easy-monitor的数据结构

**Comment by ruanzhijun** [comment]
@hyj1991 github名就是微信号

**Comment by hyj1991** [comment]
微信沟通
