### ISSUE TITLE
 Error: Cannot find module './build/profiler/v5.7.8/node-v64-linux-x64/profiler.node'

### ISSUE THREAD

**Issue by khflx** [hyj1991/easy-monitor#80]
安装这个NPM包启动时会报这个错, 仔细看了下npm安装包的过程提示, 发现有如下错误但安装完成了:(

> node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@8.9.4 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 

这似乎是这个tar包没了? 
我的环境如下: 

- npm v5.6.0
- node v8.9.4
- Linux4.10.0-38-generic  x86_64 x86_64 GNU/Linux

这台机器上有使用nvm

**Comment by hyj1991** [comment]
这个是正常的，其实不是错误，应该是 warning。
具体 node 扩展安装的机制是这样的：pre-gyp 查看有没有对应版本 + OS 下编译好的 binary -> 如果有则下载，如果没有 fallback 到 local compile。
这里因为 v8.9.4-linux-x64 下没有对应的 binary，所以下载 404，然后回退到本地编译

**Comment by hyj1991** [comment]
没什么其他问题这个 issue 我先关闭了
