### ISSUE TITLE
[RFC] CPU 使用率的差异（优化计算方式增加准确度）

### ISSUE THREAD

**Issue by suntopo** [hyj1991/easy-monitor#83]
![2018-09-18 10-47-45](https://user-images.githubusercontent.com/5196122/45661519-6c06a800-bb30-11e8-8e59-cae539a82fd1.png)
使用top命令显示我的cpu已经超过100%了, 但是监控显示在46%, 我猜是: top显示的cpu占比是node(js)自身运行+v8(c++)使用占比, monitor使用的仅仅是node(js)的占比.

能否给详细介绍下呢?

**Comment by hyj1991** [comment]
CPU 的计算在这里：https://github.com/hyj1991/easy-monitor/blob/master/src_logic/common/common.overview.js#L10
其实在 node 层算出来的值始终可能有偏差（内核精度决定的），最准确的算法得放到 c++ 扩展里面去，利用 uv_hrtime 算出程序启动到当前的时间，和系统函数 clock() 返回的程序启动到当前的 CPU 调用时间算比值。

**Comment by hyj1991** [comment]
当然从 Node v6 开始，内核在 process 上面增加了 cpuUsage() 方法，可以结合 process.hrtime() 计算相对比上述算法更精准的值，当时是因为这个项目启动的时候 Node 4 尚在 LTS 内，为了做 v4 版本的兼容这样子计算的，有空可以优化下，也欢迎 pr 哦。

**Comment by suntopo** [comment]
我上面说的的确是不对(没有对top命令很了解) top显示的是单个cpu的占用率, 比如node的cpu占有率是30%, 对于四核cpu来说top显示出来的就是120%左右.  现在的问题是, 该包统计出来的和系统显示的有差距, 可能就是你说的那个原因导致的.
![2018-09-18 11-51-26](https://user-images.githubusercontent.com/5196122/45663727-804fa280-bb3a-11e8-8908-a90b7be183fa.png)

**Comment by hyj1991** [comment]
可以先打开这个 issue，算一个优化提升的点吧，没人 pr 等我有空优化下计算方式看看能不能贴近系统显示

**Comment by suntopo** [comment]
![2018-09-18 14-48-27](https://user-images.githubusercontent.com/5196122/45669547-01b32f00-bb53-11e8-9149-6c44dc1af3c7.png)
![2018-09-18 14-56-05](https://user-images.githubusercontent.com/5196122/45669572-0c6dc400-bb53-11e8-97a5-71042b0c14c6.png)

用ab压测的时候出现了heaptotal大于rss的情况, 这个怎么解释呢, 求指导(抱大腿)

**Comment by hyj1991** [comment]
这个和 Linux/Mac 的内存机制有关系，首先你要知道 rss 是进程实际的内存占用大小。
而你在 c++ 扩展里面 malloc 一块内存，但是不使用的话，rss 是不会增加的；同样的操作在 JS 里面也一样，单纯 new 一个大数组，但是不做 fill 填充时；V8 会把申请的大数组内存记录到 heapTotal 里面（这是合理的），但是 rss 实际没有变大（或者过一会降下来，因为并没有真的使用这块内存）

**Comment by hyj1991** [comment]
进展参见 #103
