### ISSUE TITLE
实时的显示内存占用?

### ISSUE THREAD

**Issue by Fov6363** [hyj1991/easy-monitor#9]
您好,我想问一上是否支持这个功能,我选择解析类型为OS,出来是实时的,但那个出来的坐标不太明白是什么意思,这个500的单位如果是M的话,为什么就是500了?单机不应该是1.4G?希望解答一下

**Comment by hyj1991** [comment]
@Fov6363 

你将鼠标移动上去，可以看到单位的，这里对 size 做了 format，根据大小显示 KB，MB等

然后你指的 1.4G 是默认情况下单个 Node 进程的堆内分配内存限制，这里展示的是实际进程当前在使用的内存，分为:
* **heapUsed:** 当前进程正在使用的堆内内存大小
* **heapTotal:** 当前进程申请的总堆内内存大小
* **rss:** 当前进程堆外分配的内存大小，比如 buffer，或者 c++ 扩展自行分配的内存等

**Comment by Fov6363** [comment]
OK,非常感谢
