### ISSUE TITLE
通过 easy-monitor 得到了这些数据，但是 很迷茫不知道该怎么分析

### ISSUE THREAD

**Issue by JoMartinezZhu** [hyj1991/easy-monitor#91]
通过 easy-monitor 得到了这些数据，但是 很迷茫不知道该怎么分析
![image](https://user-images.githubusercontent.com/43346131/48139356-3df84580-e2e1-11e8-8518-cc332d3e7756.png)

![image](https://user-images.githubusercontent.com/43346131/48139336-3638a100-e2e1-11e8-882c-a5f9581aebf3.png)

**Comment by hyj1991** [comment]
你的 session 存到内存里面了？你是拿官方的 demo 跑线上了啊。。。
线上 session 写到 redis 去

**Comment by hyj1991** [comment]
没有其它问题我就关闭这个 issue 了

**Comment by JoMartinezZhu** [comment]
> 你的 session 存到内存里面了？你是拿官方的 demo 跑线上了啊。。。
> 线上 session 写到 redis 去

用的express-session 直接把session 存到 内存中去了，但是 存的东西不多，也会造成内存泄漏嘛？
使用 easy-monitor 怎么获取 对内存快照？

**Comment by hyj1991** [comment]
@JoMartinezZhu 内存里不会删除的，有新用户就会累加造成泄漏
easy-monitor 暂时不支持堆快照存储到本地，直接用 v8-profiler-node8 在代码里面埋点获取

**Comment by hyj1991** [comment]
嗯，使用模块前多看看文档

> Warning The default server-side session storage, MemoryStore, is purposely not designed for a production environment. It will leak memory under most conditions, does not scale past a single process, and is meant for debugging and developing.

这个中间件的 README 里面都写得很清楚了

**Comment by JoMartinezZhu** [comment]
> 嗯，使用模块前多看看文档
> 
> > Warning The default server-side session storage, MemoryStore, is purposely not designed for a production environment. It will leak memory under most conditions, does not scale past a single process, and is meant for debugging and developing.
> 
> 这个中间件的 README 里面都写得很清楚了

这个我看了，就是不明白为什么 未造成内存泄漏！

**Comment by JoMartinezZhu** [comment]
> 你去看看默认的 MemoryStore 的实现就知道了，放在全局变量里面的，因为有全局的引用，无法释放的

MemoryStore 放在全局变量里面的，假如一个用户登录 ，在session 中存信息，即使 退出登录 清空session 信息， 原来那个session 的应用也不会被删除！

**Comment by hyj1991** [comment]
不会，更多的可以去翻下 express-session 的默认 MemoryStore 实现

**Comment by JoMartinezZhu** [comment]
> 不会，更多的可以去翻下 express-session 的默认 MemoryStore 实现

谢谢,对内存泄漏这些 平时开发没有太多的关注，麻烦你了！

**Comment by JoMartinezZhu** [comment]
> 不会，更多的可以去翻下 express-session 的默认 MemoryStore 实现

我昨天晚上 用 esay-monitor 检测是  内存泄漏，今天早上 检测 状态良好，中午检测 状态是 泄漏，不是说 session 存在内存中不会被释放嘛，但是 今天早上检测确实 是 没有内存泄漏！

**Comment by JoMartinezZhu** [comment]
> > 不会，更多的可以去翻下 express-session 的默认 MemoryStore 实现
> 
> 我昨天晚上 用 esay-monitor 检测是 内存泄漏，今天早上 检测 状态良好，中午检测 状态是 泄漏，不是说 session 存在内存中不会被释放嘛，但是 今天早上检测的状态 却从 泄漏 ---> 良好 ---->泄漏,期间 服务器没有重启过！
