### ISSUE TITLE
Electron 想通过easy-monitor 分析一下性能

### ISSUE THREAD

**Issue by loveburning** [hyj1991/easy-monitor#92]
可以看到我获取到了进程 

<img width="762" alt="qq20181108-161417 2x" src="https://user-images.githubusercontent.com/24245193/48185882-5ca61d00-e371-11e8-8321-26ce323b73eb.png">
可以正常看到cpu情况

<img width="1190" alt="qq20181108-161521 2x" src="https://user-images.githubusercontent.com/24245193/48185939-88290780-e371-11e8-922d-dab5754b8979.png">
但是在CPU数据采集的火焰图上  并看不到具体的函数耗时

<img width="1133" alt="qq20181108-161836 2x" src="https://user-images.githubusercontent.com/24245193/48186098-fff73200-e371-11e8-8a23-c765fc19b3c0.png">
引入方式:

<img width="817" alt="qq20181108-161650 2x" src="https://user-images.githubusercontent.com/24245193/48186013-c1617780-e371-11e8-831c-9b639ac3b67d.png">

期待您的回复

**Comment by hyj1991** [comment]
抱歉，没有在 electron 里面测试过，理论上基于 Node 构建的应用都可以测试，你确定在做 cpu profiling 期间 electron 应用有 js 运算么？

**Comment by loveburning** [comment]
@hyj1991 是有的 我在cpu profiling 期间在频繁的操作electron  但是五分钟后 并没有任何结果

**Comment by hyj1991** [comment]
有一种可能是，electron 真正工作的进程是 fork 出来的子进程，也就是你目前嵌入 easy-monitor 的进程只是一个入口主进程，所以没有任何负载；
你可以从这个角度排查下问题，cpu profiling 必须在真正工作的那个进程上才会有结果

**Comment by loveburning** [comment]
@hyj1991 感谢 感谢  确实是这样的  我将easyMonitor()放在了子线程中  确实抓到了

**Comment by hyj1991** [comment]
ok，那我就关闭这个 issue 了
