### ISSUE TITLE
在 linux 安装 easy-monitor 时候 出错了！

### ISSUE THREAD

**Issue by JoMartinezZhu** [hyj1991/easy-monitor#93]
![image](https://user-images.githubusercontent.com/43346131/48310489-f9afc280-e5ca-11e8-92dd-3e20870f90c9.png)

**Comment by hyj1991** [comment]
没有安装 g++ 等编译扩展需要的环境，可以先了解下编译 node 扩展需要的准备工作

**Comment by JoMartinezZhu** [comment]
> 没有安装 g++ 等编译扩展需要的环境，可以先了解下编译 node 扩展需要的准备工作

两个服务器的环境是一样的，怎么会 出现这样的我呢？
