### ISSUE TITLE
如何 git clone 下来后进行本地开发新功能？

### ISSUE THREAD

**Issue by liyanlong** [hyj1991/easy-monitor#95]
目前我将项目clone 下来后，想要加一些新的特性之类的。但不知道怎么进行本地开发？

**Comment by hyj1991** [comment]
如果不涉及到 view 部分的开发的话，直接项目 clone 下来当成一个库来引用就行了；
如果涉及到 view 部分的开发的话，src_view 其实是一个单独的项目，npm run dev 启动预览，npm run build 将改动后的静态资源文件打包

**Comment by hyj1991** [comment]
能说下你大概想开发什么呢？

**Comment by liyanlong** [comment]
@hyj1991  
我看了下 package.json 文件，没有 run dev 的命令， 也没有 build 的命令。 是不是漏写了
```json
{
 "scripts": {
    "test": "egg-bin test",
    "cov": "egg-bin cov"
  }
}
```

**Comment by hyj1991** [comment]
src_view 是一个单独的 view 项目

**Comment by whtiehack** [comment]
@liyanlong   你的意思是不是想一边开发自己的项目，一边给easy-monitor添加功能？

如果是的话，你需要这样做：

把easy-monitor项目与你自己的项目放到同级目录，然后在你自己的项目目录执行 `npm link ../easy-monitor`

这样你自己项目里的 easy-monitor引用就指向你clone下来的项目了。

**Comment by liyanlong** [comment]
@whtiehack 是的，希望能直接在 该项目下，进行开发。app 实例可以相对简单。 后续有时间我研究下

**Comment by hyj1991** [comment]
先关闭了，本地开发还有其它问题可以继续讨论
