### ISSUE TITLE
Linux centos 6上安装v8-profiler-node8报错

### ISSUE THREAD

**Issue by homels-kong** [hyj1991/easy-monitor#97]

**Comment by homels-kong** [comment]
![image](https://user-images.githubusercontent.com/34707704/50210827-17363000-03b2-11e9-92df-9689294e2940.png)

**Comment by hyj1991** [comment]
这是 npm 机制的问题

![image](https://user-images.githubusercontent.com/19908330/50210905-3f259380-03b2-11e9-8be4-68a269711dae.png)

确认 package.json 只在一个地方

**Comment by homels-kong** [comment]
> 那么这个提示不存在的 package.json 到底在不在呢？

你说的这个没报了，现在报这个错：

Failed to execute '/.nvm/versions/node/v8.11.1/bin/node /home/sankuai/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/build/src/node_modules/v8-profiler-node8/build/profiler/v6.0.1/node-v57-linux-x64/profiler.node --module_name=profiler --module_path=/tmp/build/src/node_modules/v8-profiler-node8/build/profiler/v6.0.1/node-v57-linux-x64 --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_nap


npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! v8-profiler-node8@6.0.1 install: `node-pre-gyp install --fallback-to-build`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the v8-profiler-node8@6.0.1 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:

**Comment by hyj1991** [comment]
错误信息都贴下呢？只有这些么

**Comment by homels-kong** [comment]
make: *** [Release/obj.target/profiler/src/profiler.o] Error 1
make: Leaving directory `/opt/meituan/node_modules/v8-profiler-node8/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/no
de-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-431.20.3.el6.mt20161028.x86_64
gyp ERR! command "/home/.nvm/versions/node/v8.11.1/bin/node" "/home/.nvm/versions/node/v8.11.1/lib/node_
modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/node_modules/v8-
profiler-node8/build/profiler/v6.0.1/node-v57-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/opt/meit
uan/node_modules/v8-profiler-node8/build/profiler/v6.0.1/node-v57-linux-x64" "--napi_version=1" "--node_abi_napi=napi" "
--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /opt/node_modules/v8-profiler-node8
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/.nvm/versions/node/v8.11.1/bin/node /home/.nvm/v
ersions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/v8-profiler-node8/build/profiler/v6.0.1/node-v57-linux-x64/profiler.node --module_name=profiler --m
odule_path=/opt/node_modules/v8-profiler-node8/build/profiler/v6.0.1/node-v57-linux-x64 --napi_version=1 --node_
abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/node_modules/node-pre-gyp/lib/util/compile.js:83:2
9)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 2.6.32-431.20.3.el6.mt20161028.x86_64
node-pre-gyp ERR! command "/home/.nvm/versions/node/v8.11.1/bin/node" "/opt/node_modules/.bin/node-pre-g
yp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/home/.nvm/versions/node/v8.11.1/bin/node /home/.nvm/versions/node/v8.11.1/lib/node_m
odules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/v8-profile
r-node8/build/profiler/v6.0.1/node-v57-linux-x64/profiler.node --module_name=profiler --module_path=/opt/node_mo
dules/v8-profiler-node8/build/profiler/v6.0.1/node-v57-linux-x64 --napi_version=1 --node_abi_napi=napi --napi_build_vers
ion=0 --node_napi_label=node-v57' (1)
npm WARN enoent ENOENT: no such file or directory, open '/opt/package.json'
npm WARN No description
npm WARN No repository field.
npm WARN No README data
npm WARN No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@6.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@6.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by hyj1991** [comment]
看下这个呢，Linux 安装扩展环境准备：[Linux 环境准备](https://github.com/nodejs/node-gyp#on-unix)

**Comment by homels-kong** [comment]
> 看下这个呢，Linux 安装扩展环境准备：[Linux 环境准备](https://github.com/nodejs/node-gyp#on-unix)

还是一样的，报相同的错

**Comment by hyj1991** [comment]
@homels-kong 你装了 node-gyp 没有？

**Comment by homels-kong** [comment]
> @homels-kong 你装了 node-gyp 没有？

装了，全局安装的

**Comment by homels-kong** [comment]
> @homels-kong 确实看不出来是什么错误。。。这是完整的错误信息么

可以加个其他聊天工具聊么？因为有的地方有公司信息，不方面贴到这里，但是错误信息基本就是这些。

**Comment by hyj1991** [comment]
@homels-kong 加我钉钉吧：81129330

**Comment by hyj1991** [comment]
先关闭了，后续其它问题可以再打开
