### ISSUE TITLE
我的node版本6.5.0，下载的easy-monitor是2.0.1，安装后，打开12333控制台，使用一直报错如下

### ISSUE THREAD

**Issue by yuyang860521** [hyj1991/easy-monitor#98]
![image](https://user-images.githubusercontent.com/19405386/50627070-b9d2df00-0f6c-11e9-8b84-3a60a124a04d.png)

[Easy-Monitor: dashboard <23168>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <23168>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <23168>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <23168>] http.axios.detail error: TypeError: Cannot read property 'composeKey' of undefined

我安装命令是npm install easy-monitor@2.0.1， 安装完全是成功的，不报错，只是有个本来我是不带版本号的，安装的是最高版本，但是我们生产环境node是6.5.0，肯定不兼容那么高的版本，就搞了个2.0.1，但是还是和高版本遇到同样的问题，点了start就跳转回http://xx.xx.xxx.xx:12333/index这个地址，希望作者能帮助看下是啥情况，另外有没有个easy-monitor版本和node版本兼容的对应关系，就像阿里的node性能监控平台那种的对应列表

**Comment by hyj1991** [comment]
* easy-monitor 是一个正常的 npm 包啊，又不是 alinode 这样的运行时，你怎么用其它 npm 包的就怎么用这个，为什么要对应 node 版本
* 你的错误是因为你安装 v8-profiler-node8 这个包失败了

**Comment by yuyang860521** [comment]
> * easy-monitor 是一个正常的 npm 包啊，又不是 alinode 这样的运行时，你怎么用其它 npm 包的就怎么用这个，为什么要对应 node 版本
> * 你的错误是因为你安装 v8-profiler-node8 这个包失败了

请问下，v8-profiler-node8这个包不是依赖node8.0以上的版本？？一般情况下安装此包失败能给点建议不，找不到资料我缺少了啥导致安装失败啊。。。

**Comment by hyj1991** [comment]
@yuyang860521 没啊，这个模块兼容 v4 - 10，贴下安装报错信息，不然哪知道为啥安装不了

**Comment by yuyang860521** [comment]
> @yuyang860521 没啊，这个模块兼容 v4 - 10，贴下安装报错信息，不然哪知道为啥安装不了

我卸载了easy-monitor，直接重新安装最新版本，就无限循环这个，不Ctrl+C停止不了
![image](https://user-images.githubusercontent.com/19405386/50627944-d8d37000-0f70-11e9-8f42-43a03cf408ba.png)

我手工执行npm i v8-profiler-node8也是上图的问题，root最大权限用户，没有权限访问dev的目录？这个指教下呗

**Comment by hyj1991** [comment]
试下 `npm install easy-monitor --unsafe-perm`

**Comment by yuyang860521** [comment]
> 试下 `npm install easy-monitor --unsafe-perm`

用你这方法安装成功了，在这之前我是完全卸载了easy，重新安装的，也试过直接安装v8-profiler-node8也是成功的
![image](https://user-images.githubusercontent.com/19405386/50628883-015d6900-0f75-11e9-8dfc-58ea0c57d251.png)

安装完上述后，重启了一下pm2，然后点击控制台的start，看CPU，还是报如下的
![image](https://user-images.githubusercontent.com/19405386/50628969-8d6f9080-0f75-11e9-898f-69dd8c7dc0d1.png)

**Comment by hyj1991** [comment]
你看下 node_modules/easy-monitor/node_modules/v8-profiler-node8 有内容么？
启动的时候就报错了吧

**Comment by yuyang860521** [comment]
> 你看下 node_modules/easy-monitor/node_modules/v8-profiler-node8 有内容么？
> 启动的时候就报错了吧

这是启动时候的全部easy相关的信息
![image](https://user-images.githubusercontent.com/19405386/50629266-cd834300-0f76-11e9-8b90-746c50902634.png)

内容有，但是没有v8-profiler-node8这个包，这就是没安装成功的意思？
![image](https://user-images.githubusercontent.com/19405386/50629308-facff100-0f76-11e9-9d79-e670e8a304f9.png)

**Comment by yuyang860521** [comment]
上面第一个截图有问题，没截全，补一下
![image](https://user-images.githubusercontent.com/19405386/50629363-323e9d80-0f77-11e9-9e71-4e5e9876fdb5.png)

**Comment by yuyang860521** [comment]
![image](https://user-images.githubusercontent.com/19405386/50629390-4d111200-0f77-11e9-99b5-07ada4414eca.png)
上面第一个截图有问题，没截全，补一下

**Comment by hyj1991** [comment]
不是报了 error 么，没找到 profiler.node，这样吧，你手动执行 `npm install v8-profiler-node8 --unsafe-perm` 这个包看看报了啥错误

**Comment by yuyang860521** [comment]
![image](https://user-images.githubusercontent.com/19405386/50629516-d4f71c00-0f77-11e9-8bf3-023f2ae997ee.png)
不报错，是成功的，我再试下执行安装easy-monitor去

**Comment by yuyang860521** [comment]
[dev@sh-saas-node-server-qa-01 node_modules]$ sudo npm install v8-profiler-node8 --unsafe-perm

> v8-profiler-node8@6.0.1 preinstall /data/www/saas-fe-zhan-node/node_modules/easy-monitor/node_modules/.staging/v8-profiler-node8-8b4dec64
> node -e 'process.exit(0)'


> v8-profiler-node8@6.0.1 install /data/www/saas-fe-zhan-node/node_modules/easy-monitor/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[v8-profiler-node8] Success: "/data/www/saas-fe-zhan-node/node_modules/easy-monitor/node_modules/v8-profiler-node8/build/profiler/v6.0.1/node-v48-linux-x64/profiler.node" is installed via remote
easy-monitor@2.2.5 /data/www/saas-fe-zhan-node/node_modules/easy-monitor
├─┬ glob@7.1.3
│ ├── fs.realpath@1.0.0 
│ ├─┬ inflight@1.0.6 
│ │ └── wrappy@1.0.2 
│ ├── inherits@2.0.3 
│ ├─┬ minimatch@3.0.4 
│ │ └─┬ brace-expansion@1.1.11 
│ │   ├── balanced-match@1.0.0 
│ │   └── concat-map@0.0.1 
│ ├── once@1.4.0 
│ └── path-is-absolute@1.0.1 
└─┬ v8-profiler-node8@6.0.1 
  ├── nan@2.12.1 
  └─┬ node-pre-gyp@0.11.0 
    ├── detect-libc@1.0.3 
    ├─┬ mkdirp@0.5.1 
    │ └── minimist@0.0.8 
    ├─┬ needle@2.2.4 
    │ ├─┬ debug@2.6.9 
    │ │ └── ms@2.0.0 
    │ ├─┬ iconv-lite@0.4.24 
    │ │ └── safer-buffer@2.1.2 
    │ └── sax@1.2.4 
    ├─┬ nopt@4.0.1 
    │ ├── abbrev@1.1.1 
    │ └─┬ osenv@0.1.5 
    │   ├── os-homedir@1.0.2 
    │   └── os-tmpdir@1.0.2 
    ├─┬ npm-packlist@1.1.12 
    │ ├── ignore-walk@3.0.1 
    │ └── npm-bundled@1.0.5 
    ├─┬ npmlog@4.1.2 
    │ ├─┬ are-we-there-yet@1.1.5 
    │ │ ├── delegates@1.0.0 
    │ │ └─┬ readable-stream@2.3.6 
    │ │   ├── core-util-is@1.0.2 
    │ │   ├── isarray@1.0.0 
    │ │   ├── process-nextick-args@2.0.0 
    │ │   ├── string_decoder@1.1.1 
    │ │   └── util-deprecate@1.0.2 
    │ ├── console-control-strings@1.1.0 
    │ ├─┬ gauge@2.7.4 
    │ │ ├── aproba@1.2.0 
    │ │ ├── has-unicode@2.0.1 
    │ │ ├── object-assign@4.1.1 
    │ │ ├── signal-exit@3.0.2 
    │ │ ├─┬ string-width@1.0.2 
    │ │ │ ├── code-point-at@1.1.0 
    │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
    │ │ │   └── number-is-nan@1.0.1 
    │ │ ├─┬ strip-ansi@3.0.1 
    │ │ │ └── ansi-regex@2.1.1 
    │ │ └── wide-align@1.1.3 
    │ └── set-blocking@2.0.0 
    ├─┬ rc@1.2.8 
    │ ├── deep-extend@0.6.0 
    │ ├── ini@1.3.5 
    │ ├── minimist@1.2.0 
    │ └── strip-json-comments@2.0.1 
    ├── rimraf@2.6.3 
    ├── semver@5.6.0 
    └─┬ tar@4.4.8 
      ├── chownr@1.1.1 
      ├── fs-minipass@1.2.5 
      ├── minipass@2.3.5 
      ├── minizlib@1.2.1 
      ├── safe-buffer@5.1.2 
      └── yallist@3.0.3 

[dev@sh-saas-node-server-qa-01 node_modules]$

**Comment by yuyang860521** [comment]
[dev@sh-saas-node-server-qa-01 saas-fe-zhan-node]$ sudo npm install v8-profiler-node8 --unsafe-perm

> v8-profiler-node8@6.0.1 preinstall /data/www/saas-fe-zhan-node/node_modules/.staging/v8-profiler-node8-562bcdbf
> node -e 'process.exit(0)'


> v8-profiler-node8@6.0.1 install /data/www/saas-fe-zhan-node/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[v8-profiler-node8] Success: "/data/www/saas-fe-zhan-node/node_modules/v8-profiler-node8/build/profiler/v6.0.1/node-v48-linux-x64/profiler.node" is installed via remote
saas-fe-zhan-node@1.0.0 /data/www/saas-fe-zhan-node
└── v8-profiler-node8@6.0.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
[dev@sh-saas-node-server-qa-01 saas-fe-zhan-node]$

**Comment by yuyang860521** [comment]
[dev@sh-saas-node-server-qa-01 saas-fe-zhan-node]$ sudo npm install easy-monitor --unsafe-perm
saas-fe-zhan-node@1.0.0 /data/www/saas-fe-zhan-node
└─┬ easy-monitor@2.2.5 
  ├── basic-auth@1.1.0 
  ├── ejs@2.6.1 
  ├── glob@7.1.3 
  ├─┬ JSONStream@1.3.5 
  │ └── jsonparse@1.3.1 
  └── pretty-bytes@4.0.2 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
[dev@sh-saas-node-server-qa-01 saas-fe-zhan-node]$

**Comment by yuyang860521** [comment]
目前easy-monitor   v8-profiler-node8这两个都是安装成功的。。。。。

**Comment by hyj1991** [comment]
@yuyang860521 我看你的截图，安装用的是 NODE_VERSION_STRING 48 的版本，那就是 node6，然后跑的时候用 NODE_VERSION_STRING 57 的版本，这是 node8 啊

C++ addon 怎么能混用，哪个版本要用，就得用对应的 node 安装啊

**Comment by yuyang860521** [comment]
都是安装成功的，这里不生成v8-profiler-node8相关内容，这个正常么？

[dev@sh-saas-node-server-qa-01 node_modules]$ pwd
/data/www/saas-fe-zhan-node/node_modules/easy-monitor/node_modules
[dev@sh-saas-node-server-qa-01 node_modules]$ ll
total 12
drwxr-xr-x 2 dev dev 4096 Jan  3 16:57 basic-auth
drwxr-xr-x 3 dev dev 4096 Jan  3 16:57 ejs
drwxr-xr-x 2 dev dev 4096 Jan  3 16:57 glob
[dev@sh-saas-node-server-qa-01 node_modules]$

**Comment by yuyang860521** [comment]
嗯，确实sudo一加有可能用到node8了，我再排查下

**Comment by yuyang860521** [comment]
现在确认只要以下这句话过了，不报了，就应该可以了
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v6.0.1/node-v57-linux-x64/profiler.node'

我问下，他为啥还findV57，也就是node8的这个路径呢，我明明已经切到node6了

[root@sh-saas-node-server-qa-01 saas-fe-zhan-node]# node -v
v6.5.0

**Comment by hyj1991** [comment]
@yuyang860521 我也很奇怪，你要在服务器上维护多个版本，最好用 nvm，不要在线上跑多个 node 版本容易给自己挖坑

**Comment by yuyang860521** [comment]
看来是哪里的node8版本引用，没扫清。。。。。

**Comment by hyj1991** [comment]
@yuyang860521 su root，which node，看下 node8 在哪里

**Comment by yuyang860521** [comment]
我晕，我都去easy-monitor的node_modules里面手工安装v8-profiler了，而且我确认装的是48的，他还是在我启动时候去找57的。。。。
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v6.0.1/node-v57-linux-x64/profiler.node'

**Comment by yuyang860521** [comment]
[root@sh-saas-node-server-qa-01 saas-fe-zhan-node]# which node
/root/.nvm/versions/node/v6.5.0/bin/node
[root@sh-saas-node-server-qa-01 saas-fe-zhan-node]#

**Comment by yuyang860521** [comment]
![image](https://user-images.githubusercontent.com/19405386/50631711-52bf2580-0f80-11e9-997e-1e80fc306bc6.png)
感觉这个有点奇怪

**Comment by hyj1991** [comment]
。。。还有这种操作，建议你把多余的 node 都清理掉，线上不要把环境弄的太复杂

**Comment by yuyang860521** [comment]
![image](https://user-images.githubusercontent.com/19405386/50631913-1cce7100-0f81-11e9-8aa3-caf2aa8c9f71.png)
我滴天，终于可以了！把8.5删了，   再执行nvm alias default 6.5.0，把default改成6.5，就可以了！！谢咯哈！！一直帮我排查。。 有没有联系方式，加个呗，方便以后付费拜师学习。。。知识无价

**Comment by yuyang860521** [comment]
后续扩展问题，应该还有个伏笔，就是不知道启动项目时候，easy-monitor这么去找到8.5那个被我废弃的版本了。。。。理论上我node -v是  6.5他就应该找6的。。。 非得我把8删了才行。。。

**Comment by hyj1991** [comment]
你可以加我钉钉：hyj1991，问题解决了这个 issue 我关闭了
